### ISSUE TITLE
RxApp CoreDispatcher is null

### ISSUE THREAD

**Issue by saerlaith** [reactiveui/ReactiveUI#1202]
I have an issue where my app breaks as soon as I use something from Rx(UI), which is in the constructor of the first ViewModel. The cause is that the CoreDispatcher is null, and thus Rx can't schedule anything. 

Here's the exception:

```
System.TypeInitializationException: The type initializer for 'ReactiveUI.RxApp' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: dispatcher
```

Here's some stacktraces:

```
   at System.Reactive.Concurrency.CoreDispatcherScheduler..ctor(CoreDispatcher dispatcher)
   at System.Reactive.Concurrency.CoreDispatcherScheduler.get_Current()
   at ReactiveUI.PlatformRegistrations.<>c.<Register>b__0_5()
   at ReactiveUI.WaitForDispatcherScheduler.attemptToCreateScheduler()
   at ReactiveUI.PlatformRegistrations.Register(Action`2 registerFunction)
   at ReactiveUI.DependencyResolverMixins.InitializeReactiveUI(IMutableDependencyResolver resolver)
   at ReactiveUI.RxApp.<>c.<.cctor>b__0_0()
   at Splat.Locator.RegisterResolverCallbackChanged(Action callback)
   at ReactiveUI.RxApp..cctor()
```

```
   at ReactiveUI.RxApp.get_MainThreadScheduler()
   at ReactiveUI.ReactiveList`1.setupRx(IEnumerable`1 initialContents, Double resetChangeThreshold, IScheduler scheduler)
   at ReactiveUI.ReactiveList`1..ctor()
   at NewBooru.ViewModels.HamburgerViewModel..ctor()
   at NewBooru.Views.MainPage..ctor()
   at NewBooru.NewBooru_XamlTypeInfo.XamlTypeInfoProvider.Activate_31_MainPage()
   at NewBooru.NewBooru_XamlTypeInfo.XamlUserType.ActivateInstance()
```

The code where it crashes:

```
 public HamburgerViewModel()
        {
            MenuItems = new ReactiveList<MenuItem>
            {
                new MenuItem("link", "name", enum)
            };
        }
```

I'm not really sure what caused it. I'm making an UWP app (so no Xamarin) and I updated it to use RxUI 7.0. After that I got this issue. I tried assigning the dispatcher myself with:

```
var dispatcher = Windows.ApplicationModel.Core.CoreApplication.GetCurrentView().CoreWindow.Dispatcher;
var scheduler = new CoreDispatcherScheduler(dispatcher);
```

Where the dispatcher is not null. Sadly, this code crashes too. Is this actually a bug or am I forgetting some initialization step?

**Comment by ghuntley** [comment]
Hi @saerlaith.  Need a few more details. 

Debug or Release mode. 
In Simulator or on Physical device. 
X64 or ARM

**Comment by saerlaith** [comment]
@ghuntley thanks for taking a look.

Debug or Release Mode doesn't seem to make a difference.
I'm using the Local Machine option in Visual Studio, the Simulator fails to start up for me.
X64 or ARM doesn't matter either.

I'm pretty sure it happens in any build/deploy option for me.

**Comment by moswald** [comment]
@saerlaith can you post a minimal test application? I can't reproduce this on my end.

**Comment by PureWeen** [comment]
@saerlaith I'm not too sure where in the life cycle "System.Reactive.Concurrency.CoreDispatcherScheduler" gets initialized (I'm actually trying to figure this out currently in an Android app where I'm having a similar issue knowing the correct time to initialize Akavache for bootstrapping)    

If you move the VM instantiation to the Loaded Event on the view do you still get the error?  I'm not saying that's where you should be doing it, I'm just curious if you move the first access to RX a little bit later in the Life Cycle if you still get the same exception?

**Comment by saerlaith** [comment]
@PureWeen The dispatcher is null in RxApp, not in the ViewModel. The lifecycle of the view doesn't seem to have much to do with it. I've tried putting it in the Loaded event and the OnNavigatedTo method, both gave me the same error.

However, what did get it to work, is moving my bootstrapper from the constructor in App.xaml.cs to the OnLaunched method. Here's the code in the bootstrapper:

```
class AppBootstrapper
    {
        public AppBootstrapper()
        {
            RegisterDependencies().ConfigureAwait(false);
        }

        public async Task RegisterDependencies()
        {
            BlobCache.ApplicationName = "Booru";

            Locator.CurrentMutable.RegisterConstant(HockeyClient.Current, typeof(IHockeyClient));
            //Bunch more dependencies
        }
    }
```

and here's the code for App.xaml.cs:
```

sealed partial class App : Application
    {
        public App()
        {
            HockeyClient.Current.Configure("key",
               new TelemetryConfiguration()
               {
                   Collectors = WindowsCollectors.Metadata | WindowsCollectors.Session | WindowsCollectors.UnhandledException
               })
               .SetExceptionDescriptionLoader((Exception ex) =>
               {
                   return "Exception HResult: " + ex.HResult.ToString();
               });
            this.InitializeComponent();
            this.Suspending += OnSuspending;
            //Initializing here doesn't work
            var bootstrap = new AppBootstrapper();
        }

        protected override void OnLaunched(LaunchActivatedEventArgs e)
        {
#if DEBUG
            if (System.Diagnostics.Debugger.IsAttached)
            {
                this.DebugSettings.EnableFrameRateCounter = true;
            }

#endif
            Frame rootFrame = Window.Current.Content as Frame;
            // Do not repeat app initialization when the Window already has content,
            // just ensure that the window is active
            if (rootFrame == null)
            {
                // Create a Frame to act as the navigation context and navigate to the first page
                rootFrame = new Frame();
                rootFrame.NavigationFailed += OnNavigationFailed;
                if (e.PreviousExecutionState == ApplicationExecutionState.Terminated)
                {
                //TODO: Load state from previously suspended application
                }

                Window.Current.Content = rootFrame;
            }

            if (e.PrelaunchActivated == false)
            {
                if (rootFrame.Content == null)
                {
                    //This line works
                    var bootstrap = new AppBootstrapper();
                    rootFrame.Navigate(typeof (Views.MainPage), e.Arguments);
                }

                Window.Current.Activate();
            }
            BlobCache.EnsureInitialized();
        }
    }
```

I get why it works when you bootstrap in the OnLaunched event, but what I don't understand is why it did work before and now it doesn't.

**Comment by moswald** [comment]
Interesting. No, the test app I wrote does the bootstrapping in the constructor. 

```
public App()
{
    this.InitializeComponent();
    this.Suspending += OnSuspending;

    Locator.CurrentMutable.RegisterConstant(BlobCache.InMemory, typeof(IBlobCache));
    Locator.CurrentMutable.Register(() => new ArticleView(), typeof(IViewFor<ArticleViewModel>));
    Locator.CurrentMutable.Register(() => new FeedsView(), typeof(IViewFor<FeedsViewModel>));
}
```

**Comment by ghuntley** [comment]
Thanks for taking a look at this @moswald. Appreciated.
