### ISSUE TITLE
SignPackages does not throw exception when it fails

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1431]
**Do you want to request a *feature* or report a *bug*?**

Bug

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

* [x] Resolve location of JSON configuration
* [x] Make it throw if signing fails on any package.

```
========================================
SignPackages
========================================
Executing: &"C:/projects/reactiveui/SignPackages.ps1"
Submitting C:\projects\reactiveui\artifacts\ReactiveUI-AndroidSupport.8.0.0-alpha0055.nupkg for signing
Exception:System.IO.FileNotFoundException: The configuration file 'SignPackages.json' was not found and is not optional. The physical path is 'C:\projects\reactiveui\packages\SignClient\tools\SignPackages.json'.
   at Microsoft.Extensions.Configuration.Fi
leConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SignClient.Program.<DoMain>d__1.MoveNext() in C:\a\1\s\src\SignClient\Program.cs:line 80
Finished signing C:\projects\reactiveui\artifacts\ReactiveUI-AndroidSupport.8.0.0-alpha0055.nupkg
Submitting C:\projects\reactiveui\artifacts\ReactiveUI-Blend.8.0.0-alpha0055.nupkg for signing
Exception:System.IO.FileNotFoundException: The configuration file 'SignPackages.json' was not found and is not optional. The physical path is 'C:\projects\reactiveui\packages\SignClient\tools\SignPackages.json'.
   at Microsoft.Extensions.Configuration.Fi
leConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SignClient.Program.<DoMain>d__1.MoveNext() in C:\a\1\s\src\SignClient\Program.cs:line 80
Finished signing C:\projects\reactiveui\artifacts\ReactiveUI-Blend.8.0.0-alpha0055.nupkg
Submitting C:\projects\reactiveui\artifacts\ReactiveUI-Events-WPF.8.0.0-alpha0055.nupkg for signing
Exception:System.IO.FileNotFoundException: The configuration file 'SignPackages.json' was not found and is not optional. The physical path is 'C:\projects\reactiveui\packages\SignClient\tools\SignPackages.json'.
   at Microsoft.Extensions.Configuration.Fi
leConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SignClient.Program.<DoMain>d__1.MoveNext() in C:\a\1\s\src\SignClient\Program.cs:line 80
Finished signing C:\projects\reactiveui\artifacts\ReactiveUI-Events-WPF.8.0.0-alpha0055.nupkg
Submitting C:\projects\reactiveui\artifacts\ReactiveUI-Events-XamForms.8.0.0-alpha0055.nupkg for signing
Exception:System.IO.FileNotFoundException: The configuration file 'SignPackages.json' was not found and is not optional. The physical path is 'C:\projects\reactiveui\packages\SignClient\tools\SignPackages.json'.
   at Microsoft.Extensions.Configuration.Fi
leConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SignClient.Program.<DoMain>d__1.MoveNext() in C:\a\1\s\src\SignClient\Program.cs:line 80
Finished signing C:\projects\reactiveui\artifacts\ReactiveUI-Events-XamForms.8.0.0-alpha0055.nupkg
Submitting C:\projects\reactiveui\artifacts\ReactiveUI-Events.8.0.0-alpha0055.nupkg for signing
Exception:System.IO.FileNotFoundException: The configuration file 'SignPackages.json' was not found and is not optional. The physical path is 'C:\projects\reactiveui\packages\SignClient\tools\SignPackages.json'.
   at Microsoft.Extensions.Configuration.Fi
leConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SignClient.Program.<DoMain>d__1.MoveNext() in C:\a\1\s\src\SignClient\Program.cs:line 80
Finished signing C:\projects\reactiveui\artifacts\ReactiveUI-Events.8.0.0-alpha0055.nupkg
Submitting C:\projects\reactiveui\artifacts\ReactiveUI-Testing.8.0.0-alpha0055.nupkg for signing
Exception:System.IO.FileNotFoundException: The configuration file 'SignPackages.json' was not found and is not optional. The physical path is 'C:\projects\reactiveui\packages\SignClient\tools\SignPackages.json'.
   at Microsoft.Extensions.Configuration.Fi
leConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SignClient.Program.<DoMain>d__1.MoveNext() in C:\a\1\s\src\SignClient\Program.cs:line 80
Finished signing C:\projects\reactiveui\artifacts\ReactiveUI-Testing.8.0.0-alpha0055.nupkg
Submitting C:\projects\reactiveui\artifacts\ReactiveUI-Winforms.8.0.0-alpha0055.nupkg for signing
Exception:System.IO.FileNotFoundException: The configuration file 'SignPackages.json' was not found and is not optional. The physical path is 'C:\projects\reactiveui\packages\SignClient\tools\SignPackages.json'.
   at Microsoft.Extensions.Configuration.Fi
leConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SignClient.Program.<DoMain>d__1.MoveNext() in C:\a\1\s\src\SignClient\Program.cs:line 80
Finished signing C:\projects\reactiveui\artifacts\ReactiveUI-Winforms.8.0.0-alpha0055.nupkg
Submitting C:\projects\reactiveui\artifacts\ReactiveUI-WPF.8.0.0-alpha0055.nupkg for signing
Exception:System.IO.FileNotFoundException: The configuration file 'SignPackages.json' was not found and is not optional. The physical path is 'C:\projects\reactiveui\packages\SignClient\tools\SignPackages.json'.
   at Microsoft.Extensions.Configuration.Fi
leConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SignClient.Program.<DoMain>d__1.MoveNext() in C:\a\1\s\src\SignClient\Program.cs:line 80
Finished signing C:\projects\reactiveui\artifacts\ReactiveUI-WPF.8.0.0-alpha0055.nupkg
Submitting C:\projects\reactiveui\artifacts\ReactiveUI-XamForms.8.0.0-alpha0055.nupkg for signing
Exception:System.IO.FileNotFoundException: The configuration file 'SignPackages.json' was not found and is not optional. The physical path is 'C:\projects\reactiveui\packages\SignClient\tools\SignPackages.json'.
   at Microsoft.Extensions.Configuration.Fi
leConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SignClient.Program.<DoMain>d__1.MoveNext() in C:\a\1\s\src\SignClient\Program.cs:line 80
Finished signing C:\projects\reactiveui\artifacts\ReactiveUI-XamForms.8.0.0-alpha0055.nupkg
Submitting C:\projects\reactiveui\artifacts\ReactiveUI.8.0.0-alpha0055.nupkg for signing
Exception:System.IO.FileNotFoundException: The configuration file 'SignPackages.json' was not found and is not optional. The physical path is 'C:\projects\reactiveui\packages\SignClient\tools\SignPackages.json'.
   at Microsoft.Extensions.Configuration.Fi
leConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SignClient.Program.<DoMain>d__1.MoveNext() in C:\a\1\s\src\SignClient\Program.cs:line 80
Finished signing C:\projects\reactiveui\artifacts\ReactiveUI.8.0.0-alpha0055.nupkg
Sign-package complete
```

**Comment by onovotny** [comment]
the full path to the json is needed, I don't think relative paths are supported.

**Comment by onovotny** [comment]
It should return a negative error code if it fails

**Comment by ghuntley** [comment]
Resolved
