### ISSUE TITLE
build.cmd fails to execute

### ISSUE THREAD

**Issue by bradphelan** [reactiveui/ReactiveUI#1570]
**Do you want to request a *feature* or report a *bug*?**

bug ( build )

**What is the current behavior?**

build.cmd fails to build

```Generating events for 'UWP'
Failed to generate events for 'UWP'
2018-02-19 09:19:51 [Fatal] System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd'.
File name: 'C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES
secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at EventBuilder.Program.<>c__DisplayClass4_0.<ExtractEventsFromAssemblies>b__0(String x) in C:\Users\phelan\workspace\ReactiveUI\src\EventBuilder\Program.cs:line 135
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at EventBuilder.Program.ExtractEventsFromAssemblies(IPlatform platform) in C:\Users\phelan\workspace\ReactiveUI\src\EventBuilder\Program.cs:line 135
   at EventBuilder.Program.Main(String[] args) in C:\Users\phelan\workspace\ReactiveUI\src\EventBuilder\Program.cs:line 114
An error occurred when executing task 'GenerateEvents'.
```

I've followed instructions at

https://social.msdn.microsoft.com/Forums/vstudio/en-US/04d58be0-3b40-4422-a4b6-feeced03be41/could-not-find-an-existing-platform-winmd-location-?forum=visualstudiogeneral

to repair the windows software development kit but the error persists. (edited)
The file actually exists at
C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.16299.0\Windows.winmd

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Run

build.cmd 

**What is the expected behavior?**

build.cmd doesn't crash

**What is the motivation / use case for changing the behavior?**

I want to run build.cmd

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

My visual studio install is

```
Microsoft Visual Studio Professional 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Professional

Visual Basic 2017   00370-10200-08842-AA207
Microsoft Visual Basic 2017

Visual C# 2017   00370-10200-08842-AA207
Microsoft Visual C# 2017

Visual F# 4.1   00370-10200-08842-AA207
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.10.01106.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.31127.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51007.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2017.3.2    Build 111.0.20180201.63358
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

JustDecompilePackage2017 Extension   1.0
JustDecompilePackage2017 Visual Studio Extension Detailed Info

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51120.3

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.8.4-pre (3fe64e3)
Support for debugging Mono processes with Visual Studio.

Multilingual App Toolkit   4.0
Multilingual App Toolkit helps you localize your Windows Store app by providing file management, pseudo and machine translation, translation editor, and build integration. http://aka.ms/matinstall

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Project File Tools   1.0.1
Provides Intellisense and other tooling for XML based project files such as .csproj and .vbproj files.

RunCustomToolPackage Extension   1.0
RunCustomToolPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools

TargetFrameworkMigrator   1.0
Bulk Change .Net Projects Target Frameworks

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27130.2020
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput   2.5.1
Color output for build and debug windows - http://mike-ward.net/vscoloroutput

VsVim   2.5.0.0
VsVim is a Vim emulator for Visual Studio

WebJobs Tools v1.0.0   15.0.31106.0
WebJobs Tools v1.0.0

Xamarin   4.8.0.760 (fc93f3f5b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.8.188 (c5813fa34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.1.5.0 (HEAD/75f8c6838)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.6.1.4 (db807ec)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

OS and machine build info

![image](https://user-images.githubusercontent.com/17650/36368484-c36c0e0c-1557-11e8-9009-81b94c869104.png)

Visual Studio Workload

![image](https://user-images.githubusercontent.com/17650/36368548-11461d84-1558-11e8-93e0-43d81b777c05.png)

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by bradphelan** [comment]
Thanks to Dominik Mydlil

>  you need to have the 10.0.10586.0 and 10.0.14393.0 Windows 10 SDKs installed (one of those two puts the `.winmd` file there, i forget which)

**Comment by teamtam** [comment]
I experienced similar difficulties after installing the current latest SDK (10.0.16299.91). I subsequently installed 10.0.14393.0 and it is now working.
