### ISSUE TITLE
EventBuilder - Windows.winmd may not exist in the path referenced by code

### ISSUE THREAD

**Issue by rms81** [reactiveui/ReactiveUI#1627]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When executing build.cmd, the generation the execution of the EventBuilder for UWP throws an exception making the build fail.
2018-05-09 18:56:50 [Fatal] System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd'

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
run build.cmd

**What is the expected behavior?**
Event for UWP should be built

**What is the motivation / use case for changing the behavior?**

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
I was building the solution having fa780f0789954aee3f1aaa811bb448937184dfd9 as the last commit. with Windows SDK (version 10.0.16299 and 10.0.17134) installed by Visual Studio 2017.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

- Stacktrace
Executing: "src/EventBuilder/bin/Release/net461/EventBuilder.exe" --platform=uwp --reference="C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/ReferenceAssemblies/Microsoft/Framework"
Generating events for 'UWP'
Failed to generate events for 'UWP'
2018-05-09 18:56:50 [Fatal] System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd'.
2018-05-09 18:56:50 [Fatal] System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd'.
File name: 'C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd'
File name: 'C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at EventBuilder.Program.<>c__DisplayClass4_0.<ExtractEventsFromAssemblies>b__0(String x) in C:\Users\ricar\Repos\GitHub\rms\ReactiveUI\src\EventBuilder\Program.cs:line 135
   at EventBuilder.Program.<>c__DisplayClass4_0.<ExtractEventsFromAssemblies>b__0(String x) in C:\Users\ricar\Repos\GitHub\rms\ReactiveUI\src\EventBuilder\Program.cs:line 135
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at EventBuilder.Program.ExtractEventsFromAssemblies(IPlatform platform) in C:\Users\ricar\Repos\GitHub\rms\ReactiveUI\src\EventBuilder\Program.cs:line 135
   at EventBuilder.Program.ExtractEventsFromAssemblies(IPlatform platform) in C:\Users\ricar\Repos\GitHub\rms\ReactiveUI\src\EventBuilder\Program.cs:line 135
   at EventBuilder.Program.Main(String[] args) in C:\Users\ricar\Repos\GitHub\rms\ReactiveUI\src\EventBuilder\Program.cs:line 114
   at EventBuilder.Program.Main(String[] args) in C:\Users\ricar\Repos\GitHub\rms\ReactiveUI\src\EventBuilder\Program.cs:line 114
An error occurred when executing task 'GenerateEvents'.

**Comment by ghuntley** [comment]
Thx for reporting this rms. Contributor experience is something we deeply care about.
