### ISSUE TITLE
ObjectDisposedException changing visibility on WinForms with custom IoC container

### ISSUE THREAD

**Issue by vector-man** [reactiveui/ReactiveUI#1728]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using ISupportsActivation on a ViewModel with a custom DI container, changing the visibility of my main view in WinForms causes it to be disposed. I'm using my custom resolver https://github.com/vector-man/ReactiveUI.Griffin.Container/blob/master/Src/ReactiveUI.Griffin.Container/ReactiveUI.Griffin.Container/GriffinDependancyResolver.cs

Which is used with this container :https://github.com/jgauffin/Griffin.Container

I also tried an existing solution for Autofac, which resulted in the same issue. Refer to this example project for a demonstration of the issue: https://github.com/reactiveui/ReactiveUI/issues/1728#issuecomment-417247594

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1) Implement ISupportsActivation on main ViewModel. 
2) Register my View and ViewModel
3) Create a property in the ViewModel bound to the form's Visible property.
4) Change visibility in a ReactiveCommand

My ViewModel 
```
    public class MainViewModel : ReactiveObject, IMainViewModel
    {
        private bool _visible;

        public MainViewModel()
        {
            this.WhenActivated((d) =>
            {
                // Visible = true;



                d(ToggleVisibility = ReactiveCommand.Create(() =>
                {
                    Visible = false;
                }, null, RxApp.MainThreadScheduler));
            });
        }

        public ViewModelActivator Activator { get; } = new ViewModelActivator();

        public bool Visible
        {
            get { return _visible; }
            set { this.RaiseAndSetIfChanged(ref _visible, value); }
        }

        public ReactiveCommand ToggleVisibility { get; set; }
    }
```
 My view
```
  public partial class MainView : Form, IMainView
    {
        private CompositeDisposable _shutdown = new CompositeDisposable();

        public MainView()
        {
            InitializeComponent();


            this.WhenActivated((d) =>
            {
                d(this.Bind(ViewModel, vm => vm.Visible, v => v.Visible));
                d(this.BindCommand(ViewModel, vm => vm.ToggleVisibility, v => v.toolStripButtonProcess, nameof(toolStripButtonProcess.Click)));
                d(this.BindCommand(ViewModel, vm => vm.ToggleVisibility, v => v.toolStripMenuItemProcess, nameof(toolStripMenuItemProcess.Click)));
            });
        }

        public IMainViewModel ViewModel { get; set; }

        object IViewFor.ViewModel
        {
            get => ViewModel;
            set => ViewModel = (IMainViewModel)value;
        }
}
```
Program.cs
```
using Griffin.Container;
using Splat;
using System;
using System.Windows.Forms;
using UniversalPatchTools.Windows;
using UniversalPatchTools.Windows.Views;

namespace UniversalPatchTools.Windows

{
    internal static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        private static void Main()
        {
            Application.EnableVisualStyles(); 
            Application.SetCompatibleTextRenderingDefault(false); 

            var container = new ContainerRegistrar(); 
            container.RegisterModules(typeof(CommonModule).Assembly, typeof(WindowsModule).Assembly); 
            Locator.Current = new GriffinDependancyResolver(container);

            var mainView = (MainView) Locator.CurrentMutable.GetService<IMainView>();
         
            Application.Run(mainView);
            
  
            
        }
    }
}
```

WindowsModule:
```
            // MainView.
            registrar.RegisterService<IMainView>((c) =>
            {
                var owner = new MainView();
                owner.ViewModel = new MainViewModel();
                return owner;
            }, Lifetime.Transient);
```

Using my custom IoC seems to be messing things up. I'm getting an ObjectDisposedException when I press the button toggling visibility. 

**What is the expected behavior?**
Toggling visibility should not dispose the view. 

**What is the motivation / use case for changing the behavior?**

Was working before I updated to latest. NET and updated my nuget packages. 

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

Windows WinForms with 8.7.1

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

   ```
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at UniversalPatchTools.Windows.Program.Main() in F:\Documents\Visual Studio 2017\Projects\UniversalPatchTools\UniversalPatchTools.Windows\Program.cs:line 29


inner exception (ObjectDisposedException):


   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 143
   at System.Reactive.SynchronizedObserver`1.OnNextCore(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\SynchronizedObserver.cs:line 22
   at System.Reactive.ObserverBase`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 34
   at System.Reactive.Subjects.Subject.AnonymousSubject`2.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.Extensions.cs:line 167
   at ReactiveUI.ReactiveCommand`2.<Execute>b__17_3()
   at System.Reactive.Linq.ObservableImpl.Finally`1._.Dispose(Boolean disposing) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Finally.cs:line 47
   at System.Reactive.Sink`1.Dispose() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 30
   at System.Reactive.Sink`2.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 96
   at System.Reactive.Linq.ObservableImpl.Catch`2._.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Catch.cs:line 127
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Do.cs:line 42
   at System.Reactive.IdentitySink`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\IdentitySink.cs:line 15
   at System.Reactive.AutoDetachObserver`1.OnNextCore(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\AutoDetachObserver.cs:line 61
   at System.Reactive.ObserverBase`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 34
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass2_1`1.<Create>b__1(IObserver`1 observer)
   at System.Reactive.Linq.QueryLanguage.CreateWithDisposableObservable`1.SubscribeCore(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\QueryLanguage.Creation.cs:line 35
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObservableBase.cs:line 73
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 383
   at System.Reactive.TailRecursiveSink`1.Drain() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\TailRecursiveSink.cs:line 126
   at System.Reactive.TailRecursiveSink`1.Run(IEnumerable`1 sources) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\TailRecursiveSink.cs:line 32
   at System.Reactive.Linq.ObservableImpl.Concat`1.Run(_ sink) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Concat.cs:line 20
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 388
   at System.Reactive.Sink`2.Run(IObservable`1 source) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext.Run(_ sink) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Do.cs:line 22
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 388
   at System.Reactive.Linq.ObservableImpl.Catch`2._.Run(IObservable`1 source) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Catch.cs:line 104
   at System.Reactive.Linq.ObservableImpl.Catch`2.Run(_ sink) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Catch.cs:line 87
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 388
   at System.Reactive.Linq.ObservableImpl.Finally`1._.Run(IObservable`1 source) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Finally.cs:line 38
   at System.Reactive.Linq.ObservableImpl.Finally`1.Run(_ sink) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Finally.cs:line 22
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 388
   at System.Reactive.Sink`2.Run(IObservable`1 source) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.AsObservable`1.Run(_ sink) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\AsObservable.cs:line 20
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 388
   at System.Reactive.Subjects.ConnectableObservable`2.Connect() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ConnectableObservable.cs:line 44
   at System.Reactive.Linq.ObservableImpl.RefCount`1.Eager._.Run() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\RefCount.cs:line 85
   at System.Reactive.Linq.ObservableImpl.RefCount`1.Eager.Run(_ sink) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\RefCount.cs:line 34
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 388
   at System.Reactive.Sink`2.Run(IObservable`1 source) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 89
   at System.Reactive.Concurrency.ObserveOn`1.Scheduler.Run(ObserveOnObserverNew`1 sink) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Synchronization.ObserveOn.cs:line 28
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 388
   at System.Reactive.TailRecursiveSink`1.Drain() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\TailRecursiveSink.cs:line 126
   at System.Reactive.TailRecursiveSink`1.Run(IEnumerable`1 sources) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\TailRecursiveSink.cs:line 32
   at System.Reactive.Linq.ObservableImpl.Catch`1.Run(_ sink) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Catch.cs:line 22
   at System.Reactive.Producer`2.<>c.<SubscribeRaw>b__1_0(ValueTuple`2 tuple) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 121
   at System.Reactive.Concurrency.Scheduler.<>c__75`1.<ScheduleAction>b__75_0(IScheduler _, ValueTuple`2 tuple) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 65
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 107
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\LocalScheduler.cs:line 32
   at System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 61
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 119
   at System.Reactive.Producer`2.Subscribe(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 97
   at System.ObservableExtensions.Subscribe[T](IObservable`1 source) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Observable.Extensions.cs:line 37
   at ReactiveUI.ReactiveCommandBase`2.ICommandExecute(Object parameter)
   at ReactiveUI.ReactiveCommand.System.Windows.Input.ICommand.Execute(Object parameter)
   at ReactiveUI.ReactiveCommandMixins.<>c__DisplayClass0_0`1.<InvokeCommand>b__5(InvokeCommandInfo`2 ii)
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Do.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ExceptionServicesImpl.cs:line 16
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Stubs.cs:line 16
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 62
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Do.cs:line 42
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Where.cs:line 54
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 49
   at System.Reactive.IdentitySink`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\IdentitySink.cs:line 15
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Switch.cs:line 100
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 47
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 139
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 49
   at System.Reactive.IdentitySink`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\IdentitySink.cs:line 15
   at System.Reactive.Subjects.AsyncSubject`1.OnCompleted() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\AsyncSubject.cs:line 96
   at System.Reactive.Linq.QueryLanguage.<>c__189`1.<ToAsync>b__189_1(ValueTuple`2 state) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\QueryLanguage.Async.cs:line 915
   at System.Reactive.Concurrency.Scheduler.<>c__75`1.<ScheduleAction>b__75_0(IScheduler _, ValueTuple`2 tuple) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 65
   at System.Reactive.Concurrency.SynchronizationContextScheduler.<>c__DisplayClass4_0`1.<Schedule>b__0() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\SynchronizationContextScheduler.cs:line 67
   at System.Reactive.Concurrency.SynchronizationContextExtensions.<>c__DisplayClass1_0.<PostWithStartComplete>b__0(Object _) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\SynchronizationContextExtensions.cs:line 40

**Comment by glennawatson** [comment]
Might be worth copying in your callstack for that exception if you can

**Comment by glennawatson** [comment]
Have you installed the nuget package https://www.nuget.org/packages/reactiveui.winforms ?

**Comment by hack2root** [comment]
I think this is an issue with just your code.

First possibility, if you forget about AppDomain unload, if you objects are created in separate AppDomain, (you will never known whether this is a case until you absolutely shure you do, and know what are you doing this is a possiblity) using pransparent proxy pointers to access objects in separate AppDomain, when this happens, all access to any of the referenced objects fields or methods will throw ObjectDisposedException, due to the AppDomain's cleanup process.

Second, you can track the objects lifetime and prevent them from unloading using custom array of object references in you DI resolver, so reference counts will never became 0.

I got several additions:

1. add a custom reference counting, preventing from GC reallocation of claimed memory after small objects freed and falling in GC gen 1
2. add a try {... } catch (ObjectDisposedException ex) { /*log error with original call stack, then rethrow*/ throw; }
3. add a heavy bug buffer of pre=allocated objects to work with, and try to work with them, statically (using static, pre-allocatated arrays of objects, possibly expandable, i.e.  List<T>), rather allocating them dynamically, using Activator.CreateInstance

(I'm creator or DI framework https://build.experimentalcommunity.org, https://github.com/hack2root/build, and the old one (archived): https://archive.codeplex.com/?p=plugins), so probably my guessing with help to resolve issue unrelated to current used IoC mechanism.

**Comment by hack2root** [comment]
10 moths ago added IsChildContainer property here:
https://github.com/jgauffin/Griffin.Container/commit/f7bfe3c3a34a7f17375d88c842f578887c54d95a#diff-3c8c29f3efd471fca7d4e158c2a60cda

You are using Lifetime.Transient approach, so it whould be nie to remove Lifetime.Transient to fallback to default Scoped, or even think of using ExistingInstanceStrategy for an object instatiation for debugging purposes

**Comment by hack2root** [comment]
As a bonus, if you see this:

System.Threading.ExecutionContext.RunInternal

Invocation of UI controls is only available in the main thread context only, where UI was originally created, as i remember it is true for WinForms. jst because of this ObjectDsposedException. I mean, if you are holdin a weak references from another domain, this does not counts at all and all GC-ed when time comes. At the end, we all be GC-ed ;)

Have a nice day!

**Comment by hack2root** [comment]
On a second thaought,

ObjectDisposedExceptions form here

at System.Reactive.Linq.ObservableImpl.Finally`1._.Dispose(Boolean disposing)

means that you are 

1) trying to dispose object twice, once they are already disposed in Finally block of Linq Query already, or it was a temporarily usage for a Linq.
2) trying to use obejct references uoutside of using scope somewhere (ie compiler Linq queries)


So in case of Linq, probaby it is a good idea to stop using IQueryable inerface and finalize a collection using .ToList() method before it is too late (i mean if someone called inside of using, you will get objects disposed, and accessing them inside stored Linq references somewhere later will cause that bug)

Hope it will helps. 

So rethinking of Lifetime stategy fo the objects or a code modifications to prevent reference captureing inside of Linq expressins will helps, i hope

**Comment by glennawatson** [comment]
The View has some issues. 

You should move your two Bind's into the WhenActivated (you can wrap with d instead of your composite disposable). This will trigger the dispose (and stop the events from happening) when the form is unloaded.

I could imagine your VM's Visible triggering after the control has been Disposed.

**Comment by vector-man** [comment]
I stripped the shutdown part out, but the _shutdown will dispose of  the form when it is closed. Normally, my main view will never be disposed until after the app closes, so as far as I know, changing the visibility there shouldn't hurt.

**Comment by vector-man** [comment]
Updated my code above.

**Comment by vector-man** [comment]
Took your advice. This still doesn't work:

  ```
  public partial class MainView : Form, IMainView
    {
        private CompositeDisposable _shutdown = new CompositeDisposable();

        public MainView()
        {
            InitializeComponent();


            this.WhenActivated((d) =>
            {
                d(this.Bind(ViewModel, vm => vm.Visible, v => v.Visible));
                d(this.BindCommand(ViewModel, vm => vm.ToggleVisibility, v => v.toolStripButtonProcess, nameof(toolStripButtonProcess.Click)));
                d(this.BindCommand(ViewModel, vm => vm.ToggleVisibility, v => v.toolStripMenuItemProcess, nameof(toolStripMenuItemProcess.Click)));
            });
        }

        public IMainViewModel ViewModel { get; set; }

        object IViewFor.ViewModel
        {
            get => ViewModel;
            set => ViewModel = (IMainViewModel)value;
        }
```

**Comment by vector-man** [comment]
Added more details to my first post.

**Comment by vector-man** [comment]
Added the command to OP.

**Comment by glennawatson** [comment]
ReactiveCommand<Unit, Unit> for your property. Binding can fail if you use the abstract base class. It's on our books to remove it.

**Comment by glennawatson** [comment]
After after you set the Locator you need to call

InitializeSplat() and InitializeReactive() on your class that derives off IMutableDependencyResolver. They are extension methods that will register all the RxUI related classes.

**Comment by vector-man** [comment]
I've made the changes. Still failing.

```
......
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        private static void Main()
        {
            Application.EnableVisualStyles(); 
            Application.SetCompatibleTextRenderingDefault(false); 
            var container = new ContainerRegistrar(); 
            container.RegisterModules(typeof(CommonModule).Assembly, typeof(WindowsModule).Assembly);
            var resolver = new GriffinDependancyResolver(container);
            resolver.InitializeSplat();
            resolver.InitializeReactiveUI();
            Locator.Current = resolver;
            var mainView = (MainView) Locator.CurrentMutable.GetService<IMainView>();
         
            Application.Run(mainView);
            
  
            
        }
    }
}
```


```
....
        public ReactiveCommand<Unit, Unit> ToggleVisibility { get; set; }
```

**Comment by vector-man** [comment]
@hack2root I will try rewriting my resolver code and see how it goes. Thanks for your input.

**Comment by vector-man** [comment]
I think I'll just replace my container with Autofac (as there seems to be more support for how to do that) and see how that goes.

**Comment by vector-man** [comment]
I've completely swapped containers and I'm still getting the same exception (using other resolver library for Autofac). So, I don't think its coming from my code.

**Comment by glennawatson** [comment]
Might be worth creating a simple sample demonstrating your issue and put it into GitHub. Bit hard to diagnose without it just due to the oddity of your exception.

**Comment by vector-man** [comment]
Here we are. I've recreated the problem with the sample project. It has something to do with use of activation.
[ReactiveUI.Winforms.Samples-master (2).zip](https://github.com/reactiveui/ReactiveUI/files/2335455/ReactiveUI.Winforms.Samples-master.2.zip)

**Comment by vector-man** [comment]
I've updated the OP with everything I've found. It seems to only be a problem when you use ISupportsActivation on the main ViewModel.

**Comment by glennawatson** [comment]
ReactiveUI.AutoFac isn't supported by us and hasn't been updated in two years. 

https://reactiveui.net/docs/handbook/dependency-inversion/custom-dependency-inversion

**Comment by vector-man** [comment]
Well, there's definitely something strange going on, as both libs (mine and third party) result in the same exception. Might be something I forgot to do somewhere. It seems like it's related to the use of ISupportsActivation, so I may remove that until I can find a solution.

**Comment by glennawatson** [comment]
Well there's doesn't do a few steps. 

Also you're using a fairly old version of RxUI

Also you should use PackageReference over packages.config 

https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference

Also note a friend of mine had to do the following
```
f you go to Tools -> Options -> NuGet Package Manager -> General, You can change the "Default package management format" to "PackageReference". This should make that feature available to you. I had trouble finding this as well.
```

**Comment by vector-man** [comment]
Yeah, I'm using the new tech in my personal project. I quickly whipped that up from your example project, so that's why it is not updated. But, I believe it will still throw, as my personal project does using the new package format  + latest RxUi.

**Comment by glennawatson** [comment]
Alright, 
Found your issue.

You're disposing of the ReactiveCommand which is not something generally you need to do or should do.

Find attached a updated sample which uses our recommended AutoFac implementation and updated to the latest version.

[sample.zip](https://github.com/reactiveui/ReactiveUI/files/2341091/sample.zip)

**Comment by glennawatson** [comment]
See also https://github.com/cabauman/Rx.Net-ReactiveUI-CheatSheet for when to dispose and not to dispose. I think you should be able to go back to your own container class now.

**Comment by vector-man** [comment]
Awesome! Thank you!
