### ISSUE TITLE
[BUG] Can't build with XF 4.0 Stable

### ISSUE THREAD

**Issue by xamarindevelopervietnam** [reactiveui/ReactiveUI#2046]
**Describe the bug**
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void Xamarin.Forms.IShellControllerEvents::<get_HeaderChanged>b__3_0(System.EventHandler)' in assembly: 'ReactiveUI.Events.XamForms.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.IShellController::add_HeaderChanged(System.EventHandler)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Environment**
- OS: Windows
- Vs version: 16.0.4
- Version of XF:  4.0.0.425677
- Version of RxUI: 9.15.9

**Comment by glennawatson** [comment]
Our events library is always one behind the latest. We just had a checkin for 3.6 go in this morning and I will do a release later today for that.

Part of the pain will go away once I get Pharmacist finalized https://github.com/reactiveui/pharmacist

Basically it's going to replace the `.Events` packages with a msbuild task.

So that way it'll scan your NuGet references and generate Observables for you.

**Comment by xamarindevelopervietnam** [comment]
thanks @glennawatson

**Comment by glennawatson** [comment]
Resolving this, you can do something similar to what we do in our ReactiveUI.Events.XamForms project now.

https://github.com/reactiveui/ReactiveUI/blob/ee5d742751d5d1226fcce68714880955f3be6c78/src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj#L12

Include a PackageReference to "Pharmacist.MsBuild", which is a ReactiveUI project which generates observables for events for whatever PackageReference's are inside the current project.

Make sure it's in the project with XamarinForms.
