### ISSUE TITLE
[BUG] 9.22.1 crashes MSBUILD on netcoreapp3.0 preview8

### ISSUE THREAD

**Issue by vladhorby** [reactiveui/ReactiveUI#2152]
**Describe the bug**

After updating from 9.21.1 to 9.22.1 for a netcoreapp3.0 preview 8 project, MSBUILD crashes on build (Visual Studio 2019).

**Steps To Reproduce**
1. Create an empty ASP.NET CORE 3.0 project.
2. Add a nuget reference to ReactiveUI 9.21.1
3. Build - All OK.
4. Update nuget reference to ReactiveUI 9.22.1
5. Build - Getting a MSBUILD error.

.csproj file:
`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
	<ItemGroup>
    <PackageReference Include="ReactiveUI" Version="9.22.1">
		</PackageReference>
  </ItemGroup>
</Project>`

**Expected behavior**

Project should build successfully.

**Error messages**

Getting a modal dialog error message:
MSBuild.exe - "A new guard page for the stack cannot be created".

The output message:
`------ Rebuild All started: Project: Web, Configuration: Debug Any CPU ------
You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview`
`MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\[USERNAME]\AppData\Local\Temp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.`
`========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========`

MSBuild_*.failure.txt contains:

> UNHANDLED EXCEPTIONS FROM PROCESS 15672:
=====================
2019-08-28 15:52:22
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================

**Environment**

- OS:      Windows
- Version   10 Pro
- Net CORE: 3.0 Preview 8
- Visual Studio 2019 16.3.0 Preview 2 (tried 16.2.3 too)

**Additional context**

Workaround: revert to 9.21.1

**Comment by glennawatson** [comment]
I suspect this is a file system lock on your nuget files. Try doing a
reboot and try again

**Comment by glennawatson** [comment]
https://github.com/Microsoft/msbuild/issues/4141

Seems a similar issue was fixed. What version of visual studio are you using.

**Comment by vladhorby** [comment]
I've been battling with this for 2 days now - the msbuild error is not exactly helpful, so I tried a lot of stuff before narrowing it down.
Rebooted, moved back to .net core 3.0 preview 7, repaired Visual Studio installation.
The problem appears on both Visual Studio 2019 16.3.0 Preview 2 and the RTM 16.2.3 (latest versions at this moment).
I've done some more digging around - the problem appears to be in [Splat 8.3.1](https://github.com/reactiveui/splat/releases/tag/8.3.1). 
9.22.1 references Splat >= 8.3.1, while 9.21.1 referenced Splat >= 8.2.4.
In fact, it is enough to reference just Splat 8.3.1 in an empty netcoreapp3.0 project to reproduce the error.

**Comment by glennawatson** [comment]
Ah netcoreapp3.0 you probably want to do the rxui 10 preview. It has added 3.0 support. Slightly behind master but we are releasing 10 soon so then it will be all up to date. 

I just have one remaining unit test to fix.

**Comment by vladhorby** [comment]
Did a little more digging.
The .nuspec file for Splat 8.3.1 contains a new section (comparing to 8.2.4):
`    <frameworkReferences>
      <group targetFramework=".NETCoreApp3.0">
        <frameworkReference name="Microsoft.WindowsDesktop.App" />
      </group>
    </frameworkReferences>`
If I remove that section in the local cached nuget package and install the package again then the problem stops.
The framework reference seems suspicious, perhaps it was added by mistake?
Also, do you have the permissions to move this issue to the Splat repository, or should I open another issue there?

**Comment by glennawatson** [comment]
It's going to cause you issues with more than just splat.  System.Reactive in the previews does the same thing.

**Comment by glennawatson** [comment]
It is a deliberate inclusion regardless due to splat providing the .net core 3 windows support.
