### ISSUE TITLE
[BUG] ReactiveUI.dll can't be built without Xamarin.Android correctly configured

### ISSUE THREAD

**Issue by anaisbetts** [reactiveui/ReactiveUI#2197]
**Describe the bug**

Even if your target is unrelated to Android (i.e. you are trying to build ReactiveUI.dll + ReactiveUI.WPF.dll), the build will fail trying to ResolveSdks in Xamarin.Android unless you install it

**Steps To Reproduce**
1. Install VS2019 without Xamarin
1. Try to build *just* ReactiveUI.WPF
1. Build fails with a failure in Xamarin.Android's MSBuild task: 

```
Error	MSB4018	The "ResolveSdks" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Xamarin.Android.Tools.AndroidSdkWindows.<GetAllAvailableAndroidNdks>d__44.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Xamarin.Android.Tools.AndroidSdkBase.get_AllAndroidNdks()
   at Xamarin.Android.Tools.AndroidSdkBase.Initialize(String androidSdkPath, String androidNdkPath, String javaSdkPath)
   at Xamarin.Android.Tools.AndroidSdkWindows.Initialize(String androidSdkPath, String androidNdkPath, String javaSdkPath)
   at Xamarin.Android.Tools.AndroidSdkInfo..ctor(Action`2 logger, String androidSdkPath, String androidNdkPath, String javaSdkPath)
   at Xamarin.Android.Tasks.MonoAndroidHelper.RefreshAndroidSdk(String sdkPath, String ndkPath, String javaPath, TaskLoggingHelper logHelper)
   at Xamarin.Android.Tasks.ResolveSdks.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ReactiveUI	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	798	
```

**Comment by glennawatson** [comment]
We multitarget monoandroid so not sure how you can avoid building without Android?

**Comment by glennawatson** [comment]
I would argue if it is a bug it's more of a visual studio bug where you can select the tfm to build.

**Comment by dpvreony** [comment]
worth having someone extract a .vsconfig and placing in the repo? if it works for ndk's of course...

for example (taken from command line link below)

`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" export --installPath "C:\VS" --config "C:\.vsconfig"`

https://docs.microsoft.com/en-gb/visualstudio/install/import-export-installation-configurations?view=vs-2019
https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019

**Comment by glennawatson** [comment]
Was considering that and was going to make a separate task. Would have to be bare minimum so was going to setup a VM.

**Comment by dpvreony** [comment]
if vs doesn't deal with android sdk's a powershell script might be able to pull out the ndk's. or just have a script that just tries to install them and put in the "getting started". :) 

`sdkmanager --list`
`sdkmanager packages "platforms;android-28"`

https://developer.android.com/studio/command-line/sdkmanager.html

**Comment by glennawatson** [comment]
Lot of platforms other than windows we develop on but probably could be incorporated as part of the cake script.
