### ISSUE TITLE
[BUG] ReactiveCommand OnCanExecuteChanged run in wrong thread

### ISSUE THREAD

**Issue by Karnah** [reactiveui/ReactiveUI#2247]
**Describe the bug**
WPF application can be started from another application (for example from console application.) like this:
``` C#
static void Main(string[] args)
{
    var thread = new Thread(() =>
    {
        var app = new App();
        app.Run();
    });

    thread.SetApartmentState(ApartmentState.STA);
    thread.Start();
}
```
After call ```thread.Start();``` WPF window will be opened. If window contains ReactiveCommand, it will crash after click on button with next stack trace:
```
Unhandled Exception: System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Controls.Primitives.ButtonBase.get_Command()
   at System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
   at System.Windows.Controls.Primitives.ButtonBase.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.Input.CanExecuteChangedEventManager.HandlerSink.OnCanExecuteChanged(Object sender, EventArgs e)
   at ReactiveUI.ReactiveCommandBase`2.OnCanExecuteChanged(Boolean newValue) in D:\a\1\s\src\ReactiveUI\ReactiveCommand\ReactiveCommandBase.cs:line 198
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 43
   at System.Reactive.IdentitySink`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\IdentitySink.cs:line 15
   at System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive(Int32 count) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 898
   at System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive() in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 760
   at System.Reactive.Subjects.ReplaySubject`1.ReplayBase.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 275
   at System.Reactive.Subjects.ReplaySubject`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 167
   at System.Reactive.IdentitySink`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\IdentitySink.cs:line 15
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\DistinctUntilChanged.cs:line 72
   at System.Reactive.Linq.ObservableImpl.CombineLatest`3._.SecondObserver.OnNext(TSecond value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\CombineLatest.cs:line 177
   at System.Reactive.IdentitySink`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\IdentitySink.cs:line 15
   at System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive(Int32 count) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 898
   at System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive() in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 760
   at System.Reactive.Subjects.ReplaySubject`1.ReplayBase.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 275
   at System.Reactive.Subjects.ReplaySubject`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 167
   at System.Reactive.IdentitySink`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\IdentitySink.cs:line 15
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\DistinctUntilChanged.cs:line 72
   at System.Reactive.IdentitySink`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\IdentitySink.cs:line 15
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 47
   at System.Reactive.Linq.ObservableImpl.Scan`2._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Scan.cs:line 48
   at System.Reactive.SafeObserver`1.WrappingSafeObserver.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\SafeObserver.cs:line 30
   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 737
   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 685
   at System.Reactive.Concurrency.DefaultScheduler.LongRunning.LongScheduledWorkItem`1.<>c.<.ctor>b__3_0(Object thisObject) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\DefaultScheduler.cs:line 181
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.<>c.<StartThread>b__8_0(Object itemObject) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\ConcurrencyAbstractionLayerImpl.cs:line 73
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Steps To Reproduce**
1. Create WPF application. Create ViewModel with ReactiveCommand. Add button to MainWindow, bind it to command. Run application, click button -> all work fine.
2. Create console application, add reference to WPF application. Inside ```Main``` method create and run WPF application. Try click button -> application will crashed

**Expected behavior**
All work fine

**Additional context**
I create a [repro project](https://github.com/reactiveui/ReactiveUI/files/3854513/ReactiveUITestApplication.zip) for this problem. Also its worked in 9.xx versions.

**Comment by glennawatson** [comment]
You can probably set `RxApp.MainThreadScheduler` to a `DispatcherScheduler` after you create the wpf application on a separate thread.

**Comment by Karnah** [comment]
@glennawatson, wow, it's working! Thanks a lot!
My problem totally solved and I can close this issue if you think this is normal behavior. For me it was a bit unexpected problem after update version.

**Comment by glennawatson** [comment]
I will transfer this issue to the website project so that we can document this.
