### ISSUE TITLE
[BUG] Error when building the Xamarin Project in ReactiveUI.Events.XamForms package

### ISSUE THREAD

**Issue by AbhijeetChowdhury92** [reactiveui/ReactiveUI#2638]
**Describe the bug**

Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Xamarin.Forms.Expander' (defined in assembly 'ReactiveUI.Events.XamForms, Version=13.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Xamarin.Forms.Expander
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field)
   at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

- OS:        Android
- Version    11.0
- Device:   

**Additional context**

I am using latest Xamarin.Forms -v 5.0.0.1874 and ReactiveUI v 13.0.27. When building the project in Release mode I am facing this error.

**Comment by AlexanderMelchers** [comment]
+1

**Comment by AlexanderMelchers** [comment]
Work-around is to turn linking off entirely.

However, the issue here seems to be that the `Expander`-control from Xamarin Forms 4.x [has now been moved into the Xamarin Community Toolkit](https://forums.xamarin.com/discussion/186109/expander-in-xamarin-forms-5). As such, if you can life without, another way to work-around this issue is to remove `ReactiveUI.Events.XamForms` from your dependencies.

**Comment by AbhijeetChowdhury92** [comment]
Hi @AlexanderMelchers ,
Thanks for your reply. Removing ReactiveUI.Events.XamForms from dependencies seems to work.

> Work-around is to turn linking off entirely.
> 
> However, the issue here seems to be that the `Expander`-control from Xamarin Forms 4.x [has now been moved into the Xamarin Community Toolkit](https://forums.xamarin.com/discussion/186109/expander-in-xamarin-forms-5). As such, if you can life without, another way to work-around this issue is to remove `ReactiveUI.Events.XamForms` from your dependencies.

**Comment by housecode** [comment]
Hi all, 
strangely this only happens during Release and does not happen during the Debug

**Comment by xleon** [comment]
That package is deprecated AFAIK
Take a look at Pharmacist project. Setup is really simple.

**Comment by glennawatson** [comment]
The events package is always one major version behind xamarin forms. Pharmacist like @xleon  suggests will 100% match your project requirements. If you have complex nuget I would recommend making your own events project otherwise can go into your netstandard forms project.
