### ISSUE TITLE
[BUG] [Uno] [UWP] App does not start with the exception after upgrade from 15.1.1 to 16.1.1

### ISSUE THREAD

**Issue by HavenDV** [reactiveui/ReactiveUI#2914]
**Describe the bug**
The application does not start after upgrade from 15.1.1 to 16.1.1 with the following exception:
```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at ReactiveUI.Reflection.TryGetValueForPropertyChain[TValue](TValue& changeValue, Object current, IEnumerable`1 expressionChain) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\Expression\Reflection.cs:line 229
   at ReactiveUI.ObservedChangedMixin.TryGetValue[TSender,TValue](IObservedChange`2 item, TValue& changeValue) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\Mixins\ObservedChangedMixin.cs:line 105
   at ReactiveUI.ObservedChangedMixin.GetValueOrDefault[TSender,TValue](IObservedChange`2 item) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\Mixins\ObservedChangedMixin.cs:line 63
   at ReactiveUI.ReactiveNotifyPropertyChangedMixin.<>c.<NestedObservedChanges>b__5_0(IObservedChange`2 x) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\Mixins\ReactiveNotifyPropertyChangedMixin.cs:line 181
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 48
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 65
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 756
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
Exception: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))
```

**Environment**
- ReactiveUI Version:    16.1.1
- UWP Version: 10.0.19041.0

**Comment by glennawatson** [comment]
Try use reactiveui.uwp nuget

**Comment by HavenDV** [comment]
I think in this case you need to remove the uap TargetFramework from the ReactiveUI.Uno project.

**Comment by HavenDV** [comment]
This also leads to the problem of code duplication, because views have to define classes like this:
```cs
public abstract partial class ImportProjectViewBase :
    ReactiveUI.Uno.ReactiveUserControl<ViewModels.ImportProjectViewModel>
{
}
```
, but now the namespace for `ReactiveUserControl` is different for Uno and Uwp projects, which forces the user to use #ifdef
