### ISSUE TITLE
[BUG][Uno][WinUI] Don't know how to detect when ReactiveUI.Uno.RoutedViewHost is activated/deactivated

### ISSUE THREAD

**Issue by HavenDV** [reactiveui/ReactiveUI#3081]
**Describe the bug**
Trying to upgrade Uno WebAssembly project to WinUI:
```
VM103:1 fail: Microsoft.UI.Xaml.Window[0]
      Resize ignore, no current window defined
eval @ VM103:1
VM104:1 fail: Uno.UI.Dispatching.CoreDispatcher[0]
      Dispatcher unhandled exception
System.ArgumentException: Don't know how to detect when ReactiveUI.Uno.RoutedViewHost is activated/deactivated, you may need to implement IActivationForViewFetcher
   at ReactiveUI.ViewForMixins.WhenActivated(IActivatableView item, Func`1 block, IViewFor view) in /_/src/ReactiveUI/Activation/ViewForMixins.cs:line 153
   at ReactiveUI.ViewForMixins.WhenActivated(IActivatableView item, Action`1 block, IViewFor view) in /_/src/ReactiveUI/Activation/ViewForMixins.cs:line 200
   at ReactiveUI.ViewForMixins.WhenActivated(IActivatableView item, Action`1 block) in /_/src/ReactiveUI/Activation/ViewForMixins.cs:line 180
   at ReactiveUI.Uno.RoutedViewHost..ctor() in /_/src/ReactiveUI.Uwp/common/RoutedViewHost.cs:line 109
   at Ratbuddyssey.Views.MainView.InitializeComponent() in C:\Users\haven\source\repos\HavenDV\ratbuddyssey\src\apps\Ratbuddyssey.Apps.Uno.WebAssembly\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainView_78ae60a25305526d42d961b4e4668528.cs:line 59
   at Ratbuddyssey.Views.MainView..ctor() in C:\Users\haven\source\repos\HavenDV\ratbuddyssey\src\apps\Ratbuddyssey.Apps.Uno.WebAssembly\ViewBaseGenerator\H.Generators.ConstructorGenerator\Constructors.cs:line 278
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs:line 875
   at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs:line 846
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs:line 888
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type key, Func`2 valueFactory) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Collections.Concurrent\src\System\Collections\Concurrent\ConcurrentDictionary.cs:line 1161
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices(IServiceProvider provider, Type serviceType)
   at Splat.Microsoft.Extensions.DependencyInjection.MicrosoftDependencyResolver.GetServices(Type serviceType, String contract) in /_/src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs:line 107
   at Splat.Microsoft.Extensions.DependencyInjection.MicrosoftDependencyResolver.GetService(Type serviceType, String contract) in /_/src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs:line 86
   at ReactiveUI.DefaultViewLocator.AttemptViewResolution(String viewTypeName, String contract) in /_/src/ReactiveUI/View/DefaultViewLocator.cs:line 224
   at ReactiveUI.DefaultViewLocator.AttemptViewResolutionFor(Type viewModelType, String contract) in /_/src/ReactiveUI/View/DefaultViewLocator.cs:line 195
   at ReactiveUI.DefaultViewLocator.ResolveView[MainViewModel](MainViewModel viewModel, String contract) in /_/src/ReactiveUI/View/DefaultViewLocator.cs:line 100
   at Ratbuddyssey.App.GetView[MainViewModel](MainViewModel& viewModel) in C:\Users\haven\source\repos\HavenDV\ratbuddyssey\src\shared\Ratbuddyssey.Apps.Shared\App.xaml.cs:line 54
   at Ratbuddyssey.App.OnLaunched(LaunchActivatedEventArgs args) in C:\Users\haven\source\repos\HavenDV\ratbuddyssey\src\shared\Ratbuddyssey.Apps.Shared\App.xaml.cs:line 110
   at Microsoft.UI.Xaml.Application.Initialize()
   at Uno.UI.Dispatching.CoreDispatcher.InvokeOperationSafe(UIAsyncOperation operation) in C:\a\1\s\src\Uno.UI.Dispatching\Core\CoreDispatcher.cs:line 337
eval @ VM104:1
dotnet.js:1 
put_char @ dotnet.js:1
dotnet.js:1 Unhandled Exception:
put_char @ dotnet.js:1
dotnet.js:1 System.NullReferenceException: Object reference not set to an instance of an object.
put_char @ dotnet.js:1
dotnet.js:1    at Microsoft.UI.Xaml.Input.FocusManager.ReceiveFocusNative(Int32 handle)
put_char @ dotnet.js:1
dotnet.js:1 Uncaught Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.UI.Xaml.Input.FocusManager.ReceiveFocusNative(:56600/Int32 handle)
    at Object._convert_exception_for_method_call (dotnet.js:1)
    at Object._handle_exception_for_call (dotnet.js:1)
    at Function.managed__Uno_UI__Microsoft_UI_Xaml_Input_FocusManager_ReceiveFocusNative [as focusInMethod] (managed__Uno_UI__Microsoft_UI_Xaml_Input_FocusManager_ReceiveFocusNative:17)
    at onWindowBlur (Uno.UI.js:1870)
VM106:1 fail: Microsoft.UI.Xaml.Window[0]
      Resize ignore, no current window defined
```

**Steps To Reproduce**
[repro.zip](https://github.com/reactiveui/ReactiveUI/files/7652316/repro.zip)

**Environment**
- ReactiveUI Version:    17.0.13

**Comment by HavenDV** [comment]
I tried upgrading to 17.1.3, the error hasn't changed:
```
VM103:1 fail: Microsoft.UI.Xaml.Window[0]
      Resize ignore, no current window defined
eval @ VM103:1
VM104:1 fail: Uno.UI.Dispatching.CoreDispatcher[0]
      Dispatcher unhandled exception
System.ArgumentException: Don't know how to detect when ReactiveUI.Uno.RoutedViewHost is activated/deactivated, you may need to implement IActivationForViewFetcher
   at ReactiveUI.ViewForMixins.WhenActivated(IActivatableView item, Func`1 block, IViewFor view) in /_/src/ReactiveUI/Activation/ViewForMixins.cs:line 153
   at ReactiveUI.ViewForMixins.WhenActivated(IActivatableView item, Action`1 block, IViewFor view) in /_/src/ReactiveUI/Activation/ViewForMixins.cs:line 200
   at ReactiveUI.ViewForMixins.WhenActivated(IActivatableView item, Action`1 block) in /_/src/ReactiveUI/Activation/ViewForMixins.cs:line 180
   at ReactiveUI.Uno.RoutedViewHost..ctor() in /_/src/ReactiveUI.Uwp/common/RoutedViewHost.cs:line 109
   at Ratbuddyssey.Views.MainView.InitializeComponent() in C:\Users\haven\source\repos\HavenDV\ratbuddyssey\src\apps\Ratbuddyssey.Apps.Uno.WebAssembly\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainView_78ae60a25305526d42d961b4e4668528.cs:line 59
   at Ratbuddyssey.Views.MainView..ctor() in C:\Users\haven\source\repos\HavenDV\ratbuddyssey\src\apps\Ratbuddyssey.Apps.Uno.WebAssembly\ViewBaseGenerator\H.Generators.ConstructorGenerator\Constructors.cs:line 278
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs:line 875
   at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs:line 846
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs:line 888
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type key, Func`2 valueFactory) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Collections.Concurrent\src\System\Collections\Concurrent\ConcurrentDictionary.cs:line 1161
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices(IServiceProvider provider, Type serviceType)
   at Splat.Microsoft.Extensions.DependencyInjection.MicrosoftDependencyResolver.GetServices(Type serviceType, String contract) in /_/src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs:line 107
   at Splat.Microsoft.Extensions.DependencyInjection.MicrosoftDependencyResolver.GetService(Type serviceType, String contract) in /_/src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs:line 86
   at ReactiveUI.DefaultViewLocator.AttemptViewResolution(String viewTypeName, String contract) in /_/src/ReactiveUI/View/DefaultViewLocator.cs:line 224
   at ReactiveUI.DefaultViewLocator.AttemptViewResolutionFor(Type viewModelType, String contract) in /_/src/ReactiveUI/View/DefaultViewLocator.cs:line 195
   at ReactiveUI.DefaultViewLocator.ResolveView[MainViewModel](MainViewModel viewModel, String contract) in /_/src/ReactiveUI/View/DefaultViewLocator.cs:line 100
   at Ratbuddyssey.App.GetView[MainViewModel](MainViewModel& viewModel) in C:\Users\haven\source\repos\HavenDV\ratbuddyssey\src\shared\Ratbuddyssey.Apps.Shared\App.xaml.cs:line 54
   at Ratbuddyssey.App.OnLaunched(LaunchActivatedEventArgs args) in C:\Users\haven\source\repos\HavenDV\ratbuddyssey\src\shared\Ratbuddyssey.Apps.Shared\App.xaml.cs:line 110
   at Microsoft.UI.Xaml.Application.Initialize()
   at Uno.UI.Dispatching.CoreDispatcher.InvokeOperationSafe(UIAsyncOperation operation) in C:\a\1\s\src\Uno.UI.Dispatching\Core\CoreDispatcher.cs:line 337
eval @ VM104:1
dotnet.js:1 
put_char @ dotnet.js:1
dotnet.js:1 Unhandled Exception:
put_char @ dotnet.js:1
dotnet.js:1 System.NullReferenceException: Object reference not set to an instance of an object.
put_char @ dotnet.js:1
dotnet.js:1    at Microsoft.UI.Xaml.Input.FocusManager.ReceiveFocusNative(Int32 handle)
put_char @ dotnet.js:1
dotnet.js:1 Uncaught Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.UI.Xaml.Input.FocusManager.ReceiveFocusNative(:56600/Int32 handle)
    at Object._convert_exception_for_method_call (dotnet.js:1)
    at Object._handle_exception_for_call (dotnet.js:1)
    at Function.managed__Uno_UI__Microsoft_UI_Xaml_Input_FocusManager_ReceiveFocusNative [as focusInMethod] (managed__Uno_UI__Microsoft_UI_Xaml_Input_FocusManager_ReceiveFocusNative:17)
    at onWindowBlur (Uno.UI.js:1870)
VM106:1 fail: Microsoft.UI.Xaml.Window[0]
      Resize ignore, no current window defined
```
