### ISSUE TITLE
[BUG] System.ArgumentOutOfRangeException: Index was out of range

### ISSUE THREAD

**Issue by tomasfil** [reactiveui/ReactiveUI#3119]
**Describe the bug**

I am getting this from inside DynamicData wiith ReactiveUI and I am not really sure how can I affect that, or fix that:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.ObjectModel.Collection`1.RemoveAt(Int32 index)
   at DynamicData.Binding.SortedObservableCollectionAdaptor`2.DoUpdate(ISortedChangeSet`2 updates, IObservableCollection`1 list) in /_/src/DynamicData/Binding/SortedObservableCollectionAdaptor.cs:line 95
   at DynamicData.Binding.SortedObservableCollectionAdaptor`2.Adapt(ISortedChangeSet`2 changes, IObservableCollection`1 collection) in /_/src/DynamicData/Binding/SortedObservableCollectionAdaptor.cs:line 71
   at DynamicData.ObservableCacheEx.<>c__DisplayClass27_0`2.<Bind>b__1(ISortedChangeSet`2 changes) in /_/src/DynamicData/Cache/ObservableCacheEx.cs:line 691
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 48
--- End of stack trace from previous location ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
   at System.Reactive.AnonymousObserver`1.OnErrorCore(Exception error) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 73
   at System.Reactive.ObserverBase`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 59
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/AutoDetachObserver.cs:line 77
   at System.Reactive.ObserverBase`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 59
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 48
   at System.Reactive.Concurrency.Synchronize`1._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.Synchronize.cs:line 44
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 573
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 513
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Concurrency/DispatcherScheduler.cs:line 100
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Steps To Reproduce**

​It msot likely origins somewhere from this piece of code...: (I have no way to check if it is true, but in this app, there shouldnt be any other dynamic data sorting, than this)
```
            var publishedCache = this.jobHeadersCache
                .Connect()
                .Filter(jh => JobHeaderQuery.IsValidFunc(jh) && JobHeaderQuery.StatusAcceptedFunc(jh))
                .Filter(showAllBuildingsFilter)
                .Transform(jh => new JobInfoViewModel(jh, pairStatusPublishedUpdates))
                .Publish();

            publishedCache.Filter(x => x.JobHeader.DirectionFlg == JobDirection.In)
                .Sort(SortExpressionComparer<JobInfoViewModel>.Ascending(vm => vm.JobHeader.Priority).ThenBy(vm => vm.JobHeader.NeedToDate).ThenBy(vm => vm.JobHeader.DocName))
                .ObserveOn(RxApp.MainThreadScheduler)
                .Bind(out inJobInfoViewModels)
                .Subscribe();

            publishedCache.Filter(x => x.JobHeader.DirectionFlg == JobDirection.Out)
                .Sort(SortExpressionComparer<JobInfoViewModel>.Ascending(vm => vm.JobHeader.Priority).ThenBy(vm => vm.JobHeader.NeedToDate).ThenBy(vm => vm.JobHeader.DocName))
                .ObserveOn(RxApp.MainThreadScheduler)
                .Bind(out outJobInfoViewModels)
                .Subscribe();

            publishedCache.Connect();
```

**Expected behaviour**

It shouldnt try to remove something out of index range. 

It seems pretty random. I wasnt able to reproduce it. It Happened 3 times today after release for testing in production on different computers.

**Screenshots**

**Environment**

- OS:       Windows 10
- Version   20H2
- Device:   PC
- ReactiveUI Version:    16.4.15 -- I Cannot upgrade further to NET6, because oracle, or EF core is broken. (oracle/dotnet-db-samples/issues/222)

**Additional context**

**Comment by tomasfil** [comment]
I did replace this part with:
```
   this.jobHeadersCache
              .Connect()
              .Filter(jh => jh.DirectionFlg == JobDirection.In && JobHeaderQuery.IsValidFunc(jh) && JobHeaderQuery.StatusAcceptedFunc(jh))
              .Filter(showAllBuildingsFilter)
              .Sort(SortExpressionComparer<JobHeader>.Ascending(vm => vm.Priority).ThenBy(vm => vm.NeedToDate).ThenBy(vm => vm.DocName))
              .Transform(jh => new JobInfoViewModel(jh, pairStatusPublishedUpdates))
              .ObserveOn(RxApp.MainThreadScheduler)
              .Bind(out inJobInfoViewModels)
              .Subscribe();

            this.jobHeadersCache
              .Connect()
              .Filter(jh => jh.DirectionFlg == JobDirection.Out && JobHeaderQuery.IsValidFunc(jh) && JobHeaderQuery.StatusAcceptedFunc(jh))
              .Filter(showAllBuildingsFilter)
              .Sort(SortExpressionComparer<JobHeader>.Ascending(vm => vm.Priority).ThenBy(vm => vm.NeedToDate).ThenBy(vm => vm.DocName))
              .Transform(jh => new JobInfoViewModel(jh, pairStatusPublishedUpdates))
              .ObserveOn(RxApp.MainThreadScheduler)
              .Bind(out outJobInfoViewModels)
              .Subscribe();
```

I will report if that helped or not

**Comment by tomasfil** [comment]
Well. It didn't help, just did get the same crash report... Any idea what could it be?

**Comment by glennawatson** [comment]
Best to open this one over on the dynamic data repository.
