### ISSUE TITLE
[BUG] net6-android ReactiveUI.AndroidX 17.1.50 -> Xamarin.AndroidX.Core 1.7.0.1 error : java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete

### ISSUE THREAD

**Issue by AigioL** [reactiveui/ReactiveUI#3228]
**Describe the bug**
https://github.com/xamarin/AndroidX/issues/525

```
1>目标 _CompileToDalvik:
1>  Error in C:\Users\*\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.6\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class:
1>  Type com.google.common.util.concurrent.ListenableFuture is defined multiple times: C:\Users\*\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.6\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class, obj\Release\net6.0-android\lp\101\jl\libs\31DC00DFF80FA577.jar:com/google/common/util/concurrent/ListenableFuture.class
1>  Compilation failed
1>  Exception in thread "main" java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\*\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.6\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class
1>  	at com.android.tools.r8.internal.oO0.a(SourceFile:92)
1>  	at com.android.tools.r8.D8.main(D8.java:4)
1>  Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\*\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.6\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class
1>  	at Version.fakeStackEntry(Version_3.1.51.java:0)
1>  	at com.android.tools.r8.internal.oO0.a(SourceFile:68)
1>  	at com.android.tools.r8.internal.oO0.a(SourceFile:28)
1>  	at com.android.tools.r8.internal.oO0.a(SourceFile:27)
1>  	at com.android.tools.r8.internal.oO0.b(SourceFile:3)
1>  	at com.android.tools.r8.D8.a(D8.java:17)
1>  	at com.android.tools.r8.D8.a(D8.java:15)
1>  	at com.android.tools.r8.internal.oO0.a(SourceFile:84)
1>  	... 1 more
1>  Caused by: com.android.tools.r8.internal.b: Type com.google.common.util.concurrent.ListenableFuture is defined multiple times: C:\Users\*\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.6\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class, obj\Release\net6.0-android\lp\101\jl\libs\31DC00DFF80FA577.jar:com/google/common/util/concurrent/ListenableFuture.class
1>  	at com.android.tools.r8.internal.il1.a(SourceFile:14)
1>  	at com.android.tools.r8.internal.il1.a(SourceFile:22)
1>  	at com.android.tools.r8.internal.lf1.b(SourceFile:6)
1>  	at com.android.tools.r8.internal.lf1.a(SourceFile:23)
1>  	at com.android.tools.r8.internal.lf1.a(SourceFile:10)
1>  	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
1>  	at com.android.tools.r8.internal.lf1.a(SourceFile:6)
1>  	at com.android.tools.r8.graph.r2$a.f(SourceFile:4)
1>  	at com.android.tools.r8.dex.b.a(SourceFile:96)
1>  	at com.android.tools.r8.dex.b.a(SourceFile:21)
1>  	at com.android.tools.r8.D8.a(D8.java:21)
1>  	at com.android.tools.r8.D8.d(D8.java:11)
1>  	at com.android.tools.r8.D8.c(D8.java:1)
1>  	at com.android.tools.r8.internal.oO0.a(SourceFile:24)
1>  	... 5 more
1>  C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.14.106\tools\Xamarin.Android.D8.targets(79,5): error : java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\*\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.6\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar : com/google/common/util/concurrent/ListenableFuture.class
1>已完成在项目“ListenableFuture.Test.csproj”中生成目标“_CompileToDalvik”的操作 - 失败。
1>
1>已完成生成项目“ListenableFuture.Test.csproj”的操作 - 失败。
1>
1>生成失败。
1>
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.14.106\tools\Xamarin.Android.D8.targets(79,5): error : java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\*\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.6\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar : com/google/common/util/concurrent/ListenableFuture.class
```

**Steps To Reproduce**
build this project
https://github.com/BeyondDimension/AspNetCore.Mobile/blob/test-ref-err-r8/src/ListenableFuture.Test/ListenableFuture.Test.csproj#L14-L19

**Expected behaviour**

Compilation success

**Environment**

- ReactiveUI Version:    ReactiveUI.AndroidX 17.1.50

**Additional context**

https://github.com/BeyondDimension/AspNetCore.Mobile/blob/test-ref-err-r8/src/Directory.Packages.props
```
<PackageVersion Include="Xamarin.AndroidX.Camera.Camera2" Version="1.0.2.3" />
<PackageVersion Include="Xamarin.AndroidX.Camera.Lifecycle" Version="1.0.2.3" />
<PackageVersion Include="Xamarin.Google.Guava.ListenableFuture" Version="1.0.0.6" />
<PackageVersion Include="ReactiveUI.AndroidX" Version="17.1.50" />
```
**The dependency should be changed to ```Xamarin.AndroidX.Core 1.7.0``` to fix this issues**

**Comment by AigioL** [comment]
I have just tested it and it can be fixed using this set of packages
```
<PackageReference Include="Xamarin.AndroidX.Camera.Camera2" Version="1.0.2.4" />
<PackageReference Include="Xamarin.AndroidX.Camera.Lifecycle" Version="1.0.2.4" />
<PackageReference Include="Xamarin.Google.Guava.ListenableFuture" Version="1.0.0.6" />
<PackageReference Include="ReactiveUI.AndroidX" Version="17.1.50" />
<PackageReference Include="Xamarin.AndroidX.Core" Version="1.7.0.2" />
<PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.UI" Version="1.0.0.14" />
<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.4.1.1" />
<PackageReference Include="Xamarin.AndroidX.Preference" Version="1.2.0.1" />
<PackageReference Include="Xamarin.Google.Android.Material" Version="1.5.0.2" />
```

**Comment by glennawatson** [comment]
I have a PR to fix up some dependencies, just have to wait for the next maui release to happen to fix up some issues.
