### ISSUE TITLE
[BUG] ReactiveCommand OnCanExecuteChanged runs in wrong thread

### ISSUE THREAD

**Issue by Josch600** [reactiveui/ReactiveUI#3313]
**Describe the bug**
This bug is similar to reactiveui/website#382. We updated our application from ReactiveUI 13.3.2 to 16.3.10 and got the same exception when invoking an ReactiveCommand as described there:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Der aufrufende Thread kann nicht auf dieses Objekt zugreifen, da sich das Objekt im Besitz eines anderen Threads befindet.
  Source=WindowsBase
  StackTrace:
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Controls.Primitives.ButtonBase.get_Command()
   at System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
   at System.Windows.Controls.Primitives.ButtonBase.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.Input.CanExecuteChangedEventManager.HandlerSink.OnCanExecuteChanged(Object sender, EventArgs e)
   at ReactiveUI.ReactiveCommandBase`2.OnCanExecuteChanged(Boolean newValue) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\ReactiveCommand\ReactiveCommandBase.cs:line 219
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 732
   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 680
   at System.Reactive.Concurrency.DefaultScheduler.LongRunning.LongScheduledWorkItem`1.<>c.<.ctor>b__3_0(Object thisObject) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs:line 181
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.<>c.<StartThread>b__8_0(Object itemObject) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs:line 73
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

  This exception was originally thrown at this call stack:
    System.Windows.Threading.Dispatcher.VerifyAccess()
    System.Windows.DependencyObject.GetValue(System.Windows.DependencyProperty)
    System.Windows.Controls.Primitives.ButtonBase.Command.get()
    System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
    System.Windows.Controls.Primitives.ButtonBase.OnCanExecuteChanged(object, System.EventArgs)
    System.Windows.Input.CanExecuteChangedEventManager.HandlerSink.OnCanExecuteChanged(object, System.EventArgs)
    ReactiveUI.ReactiveCommandBase<TParam, TResult>.OnCanExecuteChanged(bool) in ReactiveCommandBase.cs
    System.Reactive.AnonymousSafeObserver<T>.OnNext(T) in AnonymousSafeObserver.cs
    System.Reactive.ObserveOnObserverLongRunning<TSource>.Drain() in ScheduledObserver.cs
    System.Reactive.ObserveOnObserverLongRunning<TSource>..cctor.AnonymousMethod__17_0(System.Reactive.ObserveOnObserverLongRunning<TSource>, System.Reactive.Disposables.ICancelable) in ScheduledObserver.cs
    ...
    [Call Stack Truncated] 
```

**Steps To Reproduce**
1. Build the solution [ReactiveUITestApplication.zip](https://github.com/reactiveui/website/files/7527195/ReactiveUITestApplication.zip).
2. Start the wpf application and press the button --> app crashes.

**Expected behavior**
The Exception described above does not happen.

**Environment**

- OS:       Windows 10 Enterprise 1909
- Device:   PC
- Version:   ReactiveUI 16.3.10

**Additional context**
The problem occurs on all ReactiveUI package versions starting with 14.2.1. It also occurs when RxApp.MainThreadScheduler is used.

**Comment by ChrisPulman** [comment]
Please update to ReactiveUI.Wpf V19.4.1 to resolve these issues
