### ISSUE TITLE
[Bug]: Method not found: 'Void ReactiveUI.WaitForDispatcherScheduler..ctor(System.Func`1)'. 

### ISSUE THREAD

**Issue by metju30** [reactiveui/ReactiveUI#3336]
### Describe the bug 🐞

Periodically (unknown condition) **Winforms designer** stops working for Forms (UserControls are ok)

at ReactiveUI.Winforms.Registrations.Register(Action`2 registerFunction)
at ReactiveUI.DependencyResolverMixins.ProcessRegistrationForNamespace(String namespaceName, AssemblyName assemblyName, IMutableDependencyResolver resolver) in /_/src/ReactiveUI/Mixins/DependencyResolverMixins.cs:line 153
at ReactiveUI.DependencyResolverMixins.InitializeReactiveUI(IMutableDependencyResolver resolver, RegistrationNamespace[] registrationNamespaces) in /_/src/ReactiveUI/Mixins/DependencyResolverMixins.cs:line 74
at ReactiveUI.RxApp.<>c.<.cctor>b__9_0() in /_/src/ReactiveUI/RxApp.cs:line 93
at Splat.InternalLocator.RegisterResolverCallbackChanged(Action callback) in /_/src/Splat/ServiceLocation/InternalLocator.cs:line 117
at Splat.Locator.RegisterResolverCallbackChanged(Action callback) in /_/src/Splat/ServiceLocation/Locator.cs:line 76
at ReactiveUI.RxApp..cctor() in /_/src/ReactiveUI/RxApp.cs:line 85

### Step to reproduce

1. View designer

### Screenshots 🖼️

![image](https://user-images.githubusercontent.com/11869489/183019080-bfa0e15d-467a-44bb-96b9-7073cc03ebcb.png)

### IDE

Visual studio 2019

### Operating system

Windows

### Version

10

### ReactiveUI Version

18.3.0.0

**Comment by metju30** [comment]
The reason is using: this.WhenActivated(d => { ... }); .. in BaseView **default** constructor
Solution: move this code OUT of constructor that designer uses

![image](https://user-images.githubusercontent.com/11869489/183047753-09c38eee-b81d-42e3-8d17-724b010ca723.png)

**Comment by glennawatson** [comment]
We do have in Splat.Drawing package where it has a Designer detector. So you can detect if the designer is running is another option

**Comment by ChrisPulman** [comment]
Please provide further details and ideally a repo demonstrating the issue, please also ensure that you use ObserveOn(RxApp.xxxxThreadScheduler) in your code choose the relevant Scheduler depending upon your requirements.
If further information is not provided by the end of July 2023 we will close this issue, many thanks.
