### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HarryPi** [reactiveui/ReactiveUI#3422]
### Describe the bug 🐞

When attempting to use ReactiveUI + ReactiveUI.Winforms with VSTO addins i get the following compile time error as seen on #1552

  Microsoft.VisualStudio.Tools.Office.targets(176, 9): [MSB4018] The "FindRibbons" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'Create.ExcelAddIn, Version=10.7.0.207, Culture=neutral, PublicKeyToken=e840a71a986082bc' or one of its dependencies. The system cannot find the file specified.
File name: 'Create.ExcelAddIn, Version=10.7.0.207, Culture=neutral, PublicKeyToken=e840a71a986082bc'
Server stack trace: 
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.UnitySerializationHolder.GetRealObject(StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.ResolveObjectReference(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.DeserializeObject(MemoryStream stm)
   at System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage.FixupForNewAppDomain()
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(IMessage reqMsg)
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Build.Framework.ITask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
=== Pre-bind state information ===
LOG: DisplayName = Create.ExcelAddIn, Version=10.7.0.207, Culture=neutral, PublicKeyToken=e840a71a986082bc
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Create.ExcelAddIn, Version=10.7.0.207, Culture=neutral, PublicKeyToken=e840a71a986082bc
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/Create.ExcelAddIn.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/Create.ExcelAddIn/Create.ExcelAddIn.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/Create.ExcelAddIn.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/Create.ExcelAddIn/Create.ExcelAddIn.EXE.

I have tried all the different versions as far down as v11 with no success.

### Step to reproduce

1. Create a new VSTO Addin via Visual studio
2. Add ReactiveUI and ReactiveUI.Winfors nuget
3. Try to compile

### Expected behavior

I would expect it to compile

### IDE

Visual Studio 2019

### Operating system

Windows 10, Windows 11

### ReactiveUI Version

From the latest to v11

**Comment by glennawatson** [comment]
Closing this issue as part of a cleanup of long-standing issues. VSTO addin compatibility is a niche scenario that hasn't seen follow-up. If you're still experiencing compile issues with VSTO on a current version, please open a new issue with details. Thank you for reporting it.
