### ISSUE TITLE
[Bug]: Fody BadImageFormatException When Using Trimming

### ISSUE THREAD

**Issue by mysteryx93** [reactiveui/ReactiveUI#3483]
### Describe the bug 🐞

If my project contains ReactiveUI.Fody, .NET 7 and

    <PublishTrimmed>true</PublishTrimmed>

Compiling throws this

```
  Fody: An unhandled exception occurred:
Exception:
Format of the executable (.exe) or library (.dll) is invalid.
Type:
System.BadImageFormatException
StackTrace:
   at Mono.Cecil.PE.ImageReader.ReadImage() in C:\projects\fody\cecil\Mono.Cecil.PE\ImageReader.cs:line 48
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name) in C:\projects\fody\cecil\Mono.Cecil.PE\ImageReader.cs:line 766
   at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters) in C:\projects\fody\cecil\Mono.Cecil\ModuleDefinition.cs:line 1146
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters) in C:\projects\fody\cecil\Mono.Cecil\ModuleDefinition.cs:line 1115
   at InnerWeaver.ReadModule(String assemblyFilePath, IAssemblyResolver assemblyResolver) in C:\projects\fody\FodyIsolated\ModuleReader.cs:line 30
   at InnerWeaver.ReadModule() in C:\projects\fody\FodyIsolated\ModuleReader.cs:line 10
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 100
Source:
Mono.Cecil
TargetSite:
Void ReadImage()
```

### Step to reproduce

1. Set PublishTrimmed = true
2. Add ReactiveUI.Fody (and use it?)
3. Compile

### Expected behavior

It should compile.

### IDE

Rider Windows

### Operating system

Linux

### Version

Garuda

### Device

laptop

### ReactiveUI Version

18.4.22

### Additional information ℹ️

Note that I'm using Avalonia.ReactiveUI

**Comment by mysteryx93** [comment]
Issue is not related to trimming, it's still throwing it without it. I will close this until I have a better idea what it's related to.

**Comment by glennawatson** [comment]
I really need to finish up the source generator replacement for fody, we don't really support it anymore due to it being really hard to maintain in comparison.

**Comment by mysteryx93** [comment]
I created a repo of BadImageFormatException in Avalonia using CompileBinding.

Looks like you're fine :)
