### ISSUE TITLE
[Bug]: IScreen.Router.Navigate.Execute not working with ReactiveUI On .net MAUI IOS

### ISSUE THREAD

**Issue by RAMESHKUMAR502** [reactiveui/ReactiveUI#3563]
### Describe the bug 🐞

IScreen.Router.Navigate.Execute not working with ReactiveUI On .net MAUI IOSappened!
	
Below is the Error And code Attached:

The message:	"NavigationPage must have a root Page before being used. Either call PushAsync with a valid Page, or pass a Page to the constructor before usage."

### Step to reproduce

Launch the App.
I see below the error

	The message	"NavigationPage must have a root Page before being used. Either call PushAsync with a valid Page, or pass a Page to the constructor before usage."	string

And the Navigation is not working message

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

This should happen...

### IDE

Visual Studio 2022

### Operating system

MAC

### Version

19.

### Device

IOS and Andrirod

### ReactiveUI Version

19.2.1

### Additional information ℹ️

[ReactiveUI-NAV.zip](https://github.com/reactiveui/ReactiveUI/files/11892513/ReactiveUI-NAV.zip)

**Comment by ChrisPulman** [comment]
Thank you for submitting the issue and the zip repo, I will try to take a look at this in the next few days.

**Comment by hitesh369253** [comment]
I’m having same issue, do we have any solution for this?

**Comment by DanielCauser** [comment]
Okay, I'm happy that I found this bug because I thought I was missing something in my code. I'm also having the same issue.

**Comment by RAMESHKUMAR502** [comment]
@DanielCauser  did you get any solution for the above Bug ..please do share it

**Comment by glennawatson** [comment]
We are working on it. Volunteer open source and having real lives and all that fun stuff :)

I think Chris was having issues getting the emulator to work to test.

**Comment by DanielCauser** [comment]
If it helps @glennawatson, the stack trace is bellow. Also, I was getting the exception on mac catalyst, Android and iOS.

```
Unhandled Exception:
System.InvalidOperationException: NavigationPage must have a root Page before being used. Either call PushAsync with a valid Page, or pass a Page to the constructor before usage.
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.ViewDidLoad()
   at UIKit.UIViewController.get_View()
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.get_NativeView()
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.Microsoft.Maui.IElementHandler.get_PlatformView()
   at Microsoft.Maui.Handlers.ViewHandler.MapInputTransparent(IViewHandler handler, IView view)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property)
   at Microsoft.Maui.Controls.Layout.UpdateInputTransparent(IViewHandler handler, IView layout)
   at Microsoft.Maui.Controls.Layout.MapInputTransparent(IViewHandler handler, IView layout)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer`1[[Microsoft.Maui.Controls.NavigationPage, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view, IPlatformViewHandler nativeViewHandler, Action`1 onElementChanged, NavigationPage& currentVirtualView, IPropertyMapper& _mapper, IPropertyMapper _defaultMapper, Boolean autoPackage)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ViewHandlerDelegator`1[[Microsoft.Maui.Controls.NavigationPage, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view, Action`1 onElementChanged, Boolean autoPackage)
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.Microsoft.Maui.IElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToUIViewController(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.WindowHandler.MapContent(IWindowHandler handler, IWindow window)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IWindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.SetHandler(INativeObject nativeElement, IElement element, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.SetWindowHandler(UIWindow platformWindow, IWindow window, IMauiContext context)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IApplication application, UIWindowScene windowScene, NSDictionary[] states)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IUIApplicationDelegate platformApplication, IApplication application, UIApplication uiApplication, NSDictionary launchOptions)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at ComboBoxSample.Program.Main(String[] args) in /Users/danielcauser/Downloads/ComboBoxSample/ComboBoxSample/Platforms/iOS/Program.cs:line 13 
```

**Comment by ChrisPulman** [comment]
@DanielCauser Thank you for this, confirming it's an issue with all the main MAUI targets, this is very useful, I have put aside time this weekend to look at these issues. We aim to resolve this and to get a update out as soon as possible.

**Comment by DanielCauser** [comment]
Thank you for the hard work folk! Cheers!

**Comment by RAMESHKUMAR502** [comment]
@glennawatson is there any new release for Nuget...How to get the new fix on to MAUI Application

**Comment by ChrisPulman** [comment]
I will try to get a release done shortly, just waiting for another fix to be merged.

**Comment by ChrisPulman** [comment]
FYI a release should be available in the next 30 to 40 minutes, the package is being published now.

Thank you for all who assisted to raise and resolve this issue.

**Comment by ChrisPulman** [comment]
Please use the next release version which will come out today, 19.3.2 has an issue which has now been resolved in the next release

**Comment by RAMESHKUMAR502** [comment]
@ChrisPulman  I ma seeing same issues 
 HostScreen.Router.Navigate.Execute(new AnotherViewModel2())
and HostScreen.Router.NavigateAndReset.Execute(new AnotherViewModel())) 

are not working they are not navigating to the page ..i see same Exeption ,Can You please test with the same I tested on IOS Simulator 16.

**Please find the Execption and Code attcahed**
<img width="1118" alt="Screenshot 2023-07-09 at 3 47 18 PM" src="https://github.com/reactiveui/ReactiveUI/assets/5734910/ca30acb6-2ebd-49de-9daf-33a310c409b1">

[ReactiveUI-NAVv2.zip](https://github.com/reactiveui/ReactiveUI/files/11994926/ReactiveUI-NAVv2.zip)

**Comment by ChrisPulman** [comment]
I will take a look with the attached code.

**Comment by ChrisPulman** [comment]
@RAMESHKUMAR502 Can you confirm that this is now only an issue with iOS as previously it was said to be an issue with Android too which proved true. There was no root page being set, the update from yesterday should have resolved this issue.

**Comment by ChrisPulman** [comment]
@RAMESHKUMAR502 in your example you have a local copy of the old RoutedViewHost please try this version instead 
[ReactiveUI-NAV-V3.zip](https://github.com/reactiveui/ReactiveUI/files/11995460/ReactiveUI-NAV-V3.zip)

**Comment by ChrisPulman** [comment]
I currently don't have access to my Apple Developer Account as Apple decided to kindly lock it for me, I am waiting for them to resolve this, its already been a week as I was intending to look at this last weekend.

When it was specified that the same issue existed on Android I proceeded to use Android and Windows as the test platforms leading to the same issues as reported on iOS and the resolution as created yesterday.

As a result we will need more details from the exceptions and if possible the line numbers that are causing the issues in ReactiveUI. We want to resolve this, so any assistance is appreciated.

### NOTE
You should no longer need to include both the `ReactiveUI.Maui` and `ReactiveUI.WinUI` packages, I could see that there was an issue with Schedulers previously where the Maui-WinUI version would have been missing the windows Scheduler.
For Windows targets where you intend to target both WinUI and Maui-WinUI you should have two separate projects, 1 with the `<UseMaui>true</UseMaui>` for Maui-WinUI with the `ReactiveUI.Maui` package and the other `<UseWinUI>true</UseWinUI>` for the WinUI only version with the `ReactiveUI.WinUI` package.

**Comment by RAMESHKUMAR502** [comment]
@ChrisPulman I have tested with the above-attached project. The app is getting crashed on every launch on both IOS and Android below are the Carsh details.

![image](https://github.com/reactiveui/ReactiveUI/assets/5734910/e87e6782-5b0c-4752-bb78-1d20c93931ec)

we are using Ios and Andriod we are using only IOS and Andriod. The issue is with **ReactiveUI.Maui****---Specified cast is not valid.**

Can you please test on Android and IOS?

**Comment by ChrisPulman** [comment]
@RAMESHKUMAR502 This is a new issue, and different to the reported one, something is trying to cast from type A to type B and failing, thankyou for the update, I will take another look this evening as it can be replicated with Android and iOS, I will need to test with Windows too to ensure that any changes are applicable for all targeted OS's.
Is there any particular sequence of events that cause this exception?

**Comment by ChrisPulman** [comment]
PS: The stack trace text of the exception would be nice as this will give the line numbers involved in the exception and guide us to the issue faster.

**Comment by RAMESHKUMAR502** [comment]
**Please find the Stack Trace Below**

"   at ReactiveUI.Maui.ReactiveContentPage`1[[MauiApp5.ViewModels.AnotherViewModel2, MauiApp5, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReactiveUI.IViewFor.set_ViewModel(Object value) in /_/src/ReactiveUI.Maui/ReactiveContentPage.cs:line 43\n   at ReactiveUI.Maui.RoutedViewHost.InvalidateCurrentViewModel() in /_/src/ReactiveUI.Maui/RoutedViewHost.cs:line 249\n   at ReactiveUI.Maui.RoutedViewHost.<.ctor>b__2_8(Unit _) in /_/src/ReactiveUI.Maui/RoutedViewHost.cs:line 122\n   at System.Reactive.AnonymousSafeObserver`1[[System.Reactive.Unit, System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].OnNext(Unit value)\n   at System.Reactive.Sink`1[[System.Reactive.Unit, System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].ForwardOnNext(Unit value)\n   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._[[System.Reactive.Unit, System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].OnNext(Unit value)\n   at System.Reactive.Subjects.Subject`1[[System.Reactive.Unit, System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].OnNext(Unit value)\n   at ReactiveUI.Maui.RoutedViewHost.<>c__DisplayClass2_1.<.ctor>g__Handler|14(Object sender, NavigationEventArgs e) in /_/src/ReactiveUI.Maui/RoutedViewHost.cs:line 105\n   at Microsoft.Maui.Controls.NavigationPage.RemoveAsyncInner(Page page, Boolean animated, Boolean fast, Boolean requestedFromHandler)"

**Comment by ChrisPulman** [comment]
@RAMESHKUMAR502 Excellent, thank you for this, InvalidateCurrentViewModel is most likely the issue here, I will see what is happening, it may be trying to write directly over an existing item causing the issue.

**Comment by ChrisPulman** [comment]
19.4.x should be released shortly, please try this and report back on your findings, many thanks.

**Comment by ChrisPulman** [comment]
We will close this based on no news is good news, please open a new issue if further problems occur. Many thanks again.

**Comment by RAMESHKUMAR502** [comment]
Thanks, @ChrisPulman  i have tested the Sample it's working for me..,if any issue i will get back to you
