### ISSUE TITLE
WhenAnyDynamic does not work with c# DynamicObjects

### ISSUE THREAD

**Issue by bradphelan** [reactiveui/ReactiveUI#380]
I have a c# dynamic object which I have added a property `A` to previously. I then try to do

```
     var d0 = this.WhenAnyDynamic(new[] { prop }, p => p.Value)
            .Subscribe(v => lens.Current = ( T ) v);
```

where 

```
prop = "A";
```

but I crash with

```
Test Name:  ShouldWork
Test FullName:  ReactiveUI.Ext.Spec.DynamicLens2INPCSpec.ShouldWork
Test Source:    c:\Users\phelan\workspace\WeinCad.Net\ReactiveUI.Ext.Spec\DynamicLens2INPCSpec.cs : line 37
Test Outcome:   Failed
Test Duration:  0:00:00.667

Result Message: System.ArgumentException : Type 'ReactiveUI.Ext.DynamicLens2INPC' must have a property 'A'
Result StackTrace:  
at ReactiveUI.Reflection.GetValueFetcherOrThrow(Type type, String propName)
   at ReactiveUI.Reflection.TryGetValueForPropertyChain[TValue](TValue& changeValue, Object current, String[] propNames)
   at ReactiveUI.ObservedChangedMixin.TryGetValue[TSender,TValue](IObservedChange`2 This, TValue& changeValue)
   at ReactiveUI.ObservedChangedMixin.fillInValue[TSender,TValue](IObservedChange`2 This)
   at ReactiveUI.ReactiveNotifyPropertyChangedMixin.observedChangeFor(String propertyName, IObservedChange`2 sourceChange)
   at ReactiveUI.ReactiveNotifyPropertyChangedMixin.nestedObservedChanges(String propertyName, IObservedChange`2 sourceChange, Boolean beforeChange)
   at ReactiveUI.ReactiveNotifyPropertyChangedMixin.<>c__DisplayClassb`2.<>c__DisplayClassd.<SubscribeToExpressionChain>b__6(IObservedChange`2 y)
   at System.Reactive.Linq.Observαble.Select`2._.OnNext(TSource value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.Stubs.<.cctor>b__1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.Observαble.Select`2._.OnError(Exception error)
   at System.Reactive.Linq.Observαble.DistinctUntilChanged`2._.OnError(Exception error)
   at System.Reactive.Linq.Observαble.Select`2._.OnError(Exception error)
   at System.Reactive.Linq.Observαble.Where`1._.OnError(Exception error)
   at System.Reactive.Linq.Observαble.Switch`1._.OnError(Exception error)
   at System.Reactive.Linq.Observαble.Select`2._.OnNext(TSource value)
   at System.Reactive.Linq.Observαble.Return`1._.Invoke()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.ImmediateScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action)
   at System.Reactive.Linq.Observαble.Return`1._.Run()
   at System.Reactive.Linq.Observαble.Return`1.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Linq.Observαble.Select`2.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Linq.Observαble.Switch`1._.Run()
   at System.Reactive.Linq.Observαble.Switch`1.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Linq.Observαble.Where`1.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Linq.Observαble.Select`2.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Linq.Observαble.DistinctUntilChanged`2.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Linq.Observαble.Select`2.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.Run(IScheduler _, State x)
   at System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.Reactive.Producer`1.Subscribe(IObserver`1 observer)
   at System.ObservableExtensions.Subscribe[T](IObservable`1 source, Action`1 onNext)
   at ReactiveUI.Ext.DynamicLens2INPC.Add[T](ILens`1 lens) in c:\Users\phelan\workspace\WeinCad.Net\ReactiveUI.Ext\DynamicLens2INPC.cs:line 22
   at ReactiveUI.Ext.Spec.DynamicLens2INPCSpec.ShouldWork() in c:\Users\phelan\workspace\WeinCad.Net\ReactiveUI.Ext.Spec\DynamicLens2INPCSpec.cs:line 48
```

Note my object definately supports INPC on "A" changing cause this code works

```
        this.PropertyChanged += ( o, e ) =>
        {
            if ( e.PropertyName == prop )
            {
                lens.Current = ( T ) GetPropertyValue(prop);
            }
        };
```

**Comment by glennawatson** [comment]
Closing this issue as part of a cleanup of long-standing issues. This was reported in 2013 against a very different version of ReactiveUI. The `WhenAnyDynamic` API and the reflection subsystem have been significantly reworked since then. If you're still experiencing this issue on a current version of ReactiveUI, please open a new issue with a reproduction sample. Thank you for reporting it.
