### ISSUE TITLE
[Bug]: iOS BindCommand throws exception when executing on iPad (device)

### ISSUE THREAD

**Issue by yvcabrerago** [reactiveui/ReactiveUI#3877]
### Describe the bug 🐞

Using Avalonia 11.0.10, when binding a command using BindCommand in the code behind of the view as follows:

```
public MainView()
{
    this.WhenActivated(disposed =>
    {
        this.BindCommand(ViewModel, vm => vm.MyCommand, v => v.Button).DisposeWith(disposed);
    });
    
    InitializeComponent();
}
```

The following exception is being throw: 

Terminating app due to uncaught exception 'System.ArgumentException', reason: 'Property set method not found. (System.ArgumentException)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object , Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Reflection.PropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at ReactiveUI.CreatesCommandBindingViaCommandParameter.BindCommandToObject(ICommand command, Object target, IObservable`1 commandParameter) in /_/src/ReactiveUI/Bindings/Command/CreatesCommandBindingViaCommandParameter.cs:line 60
   at ReactiveUI.CreatesCommandBinding.BindCommandToObject(ICommand command, Object target, IObservable`1 commandParameter) in /_/src/ReactiveUI/Bindings/Command/CreatesCommandBinding.cs:line 39

### Step to reproduce

1. Create a Cross Platform Avalonia Application.
2. Create a ReactiveCommand and bind to a control in the code behing file of the view.
3. Run the app using a iPad.

### Reproduction repository

https://github.com/yvcabrerago/AvaloniaReactiveApplication

### Expected behavior

The application should not crash.

### IDE

Rider macOS

### Device

IPad 10th generation, IPadOS 17.1.1

### ReactiveUI Version

18.3.1

**Comment by ChrisPulman** [comment]
Please could you try updating ReactiveUI to 20.1.1, let me know if this solves your issue, thank you.

**Comment by yunior-cabrera** [comment]
Tested again with ReactiveUI v20.1.1, the issue is still happening. As a workaround, passing the name of the event as the fourth argument works:
`this.BindCommand(ViewModel, vm => vm.MyCommand, v => v.Button, nameof(Button.Click)).DisposeWith(disposed);`

**Comment by glennawatson** [comment]
Closing this issue as part of a cleanup of long-standing issues. For Avalonia-related issues, please use the new official repository: https://github.com/reactiveui/ReactiveUI.Avalonia — the out-of-sync method issues have been fixed there. A workaround for the original issue is to pass the event name explicitly to BindCommand. Thank you for reporting it.

<blockquote><img src="https://opengraph.githubassets.com/cf1601d2864972616db63dfbd64eb4069d6fd528692d5a8df3f25b294c8c45c4/reactiveui/ReactiveUI.Avalonia" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/reactiveui/ReactiveUI.Avalonia">GitHub - reactiveui/ReactiveUI.Avalonia: Avalonia related components for the ReactiveUI family</a></strong></div><div>Avalonia related components for the ReactiveUI family - reactiveui/ReactiveUI.Avalonia</div></blockquote>
