### ISSUE TITLE
Application crash updating to 5.5

### ISSUE THREAD

**Issue by bradphelan** [reactiveui/ReactiveUI#555]
I've updated from 5.4 to 5.5 and I get the following error when my UI is raised.

![image](https://cloud.githubusercontent.com/assets/17650/2655533/acf6f8f4-bfe7-11e3-8bf7-7f0a1774c03a.png)

	System.InvalidOperationException was unhandled
	  HResult=-2146233079
	  Message='VisualCue' name cannot be found in the name scope of 'System.Windows.Controls.ControlTemplate'.
	  Source=PresentationFramework
	  StackTrace:
	       at System.Windows.Media.Animation.Storyboard.ResolveTargetName(String targetName, INameScope nameScope, DependencyObject element)
	       at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
	       at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
	       at System.Windows.Media.Animation.Storyboard.BeginCommon(DependencyObject containingObject, INameScope nameScope, HandoffBehavior handoffBehavior, Boolean isControllable, Int64 layer)
	       at System.Windows.Media.Animation.BeginStoryboard.Begin(DependencyObject targetObject, INameScope nameScope, Int64 layer)
	       at System.Windows.Media.Animation.BeginStoryboard.Invoke(FrameworkElement fe, FrameworkContentElement fce, Style targetStyle, FrameworkTemplate frameworkTemplate, Int64 layer)
	       at System.Windows.StyleHelper.InvokeEventTriggerActions(FrameworkElement fe, FrameworkContentElement fce, Style ownerStyle, FrameworkTemplate frameworkTemplate, Int32 childIndex, RoutedEvent Event)
	       at System.Windows.StyleHelper.ExecuteEventTriggerActionsOnContainer(Object sender, RoutedEventArgs e)
	       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
	       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
	       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
	       at System.Windows.Data.BindingExpression.OnTargetUpdated(DependencyObject d, DependencyProperty dp)
	       at System.Windows.Data.BindingExpression.OnTargetUpdated()
	       at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
	       at System.Windows.Data.BindingExpression.Activate(Object item)
	       at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
	       at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
	       at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
	       at MS.Internal.Data.DataBindEngine.Run(Object arg)
	       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	       at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
	       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
	       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	       at System.Windows.Threading.DispatcherOperation.Invoke()
	       at System.Windows.Threading.Dispatcher.ProcessQueue()
	       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	       at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
	       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
	       at System.Windows.Threading.Dispatcher.Run()
	       at System.Windows.Application.RunDispatcher(Object ignore)
	       at System.Windows.Application.RunInternal(Window window)
	       at System.Windows.Application.Run(Window window)
	       at System.Windows.Application.Run()
	       at WeinCad.Net.WeinCadApplication.Main() in c:\Users\phelan\workspace\WeinCad.Net\WeinCad.Net\obj\Debug\App.g.cs:line 0
	       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
	       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
	       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
	       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
	       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	       at System.Threading.ThreadHelper.ThreadStart()
	  InnerException: 

I've reverted the upgrade and tested and all is fine then reapply the upgrade and I get the above error again. Not sure what it might be. I am using some storyboard animations but what has that got to do with RUI? Nothing in the stack trace suggests interference from RUI.

**Comment by jlaanstra** [comment]
This issue has not had any activity for a year. Please reopen if this is still causing problems.
