### ISSUE TITLE
(WPF) UI Thread exception when changing bound boolean on VM from background thread

### ISSUE THREAD

**Issue by sickboy** [reactiveui/ReactiveUI#798]
View:
```
this.Bind(ViewModel, vm => vm.IsOpen, v => v.IsOpen);
...
        public IStatusViewModel ViewModel {
            get { return (IStatusViewModel) GetValue(ViewModelProperty); }
            set { SetValue(ViewModelProperty, value); }
        }
        object IViewFor.ViewModel {
            get { return ViewModel; }
            set { ViewModel = (IStatusViewModel) value; }
        }
```

ViewModel:
```
Task.Run(() => IsOpen = true);
```

Results in: 
```
2015-01-26 15:53:48.8453|ERROR|Six.Core.Logging.MainLog|Abnormal termination: Type: System.Exception
Message:
    An OnError occurred on an object (usually ObservableAsPropertyHelper) that would break a binding or command. To prevent this, Subscribe to the ThrownExceptions property of your objects
.....
    Type: System.InvalidOperationException
    Message:
        The calling thread cannot access this object because a different thread owns it.
...
           at System.Windows.Threading.Dispatcher.VerifyAccess()
           at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
           at Six.Presentation.Play.Views.Overlays.StatusView.get_ViewModel() in p:\P\sn\withSIX.Desktop\src\Six.Presentation.Play\Views\Overlays\StatusView.xaml.cs:line 73
           at Six.Presentation.Play.Views.Overlays.StatusView.ReactiveUI.IViewFor.get_ViewModel() in p:\P\sn\withSIX.Desktop\src\Six.Presentation.Play\Views\Overlays\StatusView.xaml.cs:line 77
           at ReactiveUI.PropertyBinderImplementation.<>c__DisplayClass8`5.<Bind>b__5(Boolean isVm)
           at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
           at System.Reactive.Stubs.<.cctor>b__1(Exception ex)
           at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
           at System.Reactive.Linq.ObservableImpl.RefCount`1._.OnError(Exception error)
           at System.Reactive.Subjects.Subject`1.OnError(Exception error)
           at System.Reactive.Linq.ObservableImpl.AsObservable`1._.OnError(Exception error)
           at System.Reactive.Linq.ObservableImpl.Where`1._.OnError(Exception error)
           at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Merge`1._.Iter.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Switch`1._.Iter.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Where`1._.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Switch`1._.Iter.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Concat`1._.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Where`1._.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Cast`2._.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.RefCount`1._.OnNext(TSource value)
           at System.Reactive.Observer`1.OnNext(T value)
           at System.Reactive.Subjects.Subject`1.OnNext(T value)
           at System.Reactive.Linq.ObservableImpl.AsObservable`1._.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.SelectMany`2.NoSelectorImpl.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Buffer`2.Beta.Omega.OnNext(TBufferClosing value)
           at System.Reactive.Linq.ObservableImpl.Merge`1._.Iter.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
           at System.Reactive.Linq.ObservableImpl.Where`1._.OnNext(TSource value)
           at System.Reactive.Observer`1.OnNext(T value)
           at System.Reactive.Subjects.Subject`1.OnNext(T value)
           at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.notifyObservable[T](TSender rxObj, T item, ISubject`1 subject)
```

The view is created in the ShellView.xaml, and bound once (the VM instance never changes) in the ShellView.xaml.cs:
```
this.OneWayBind(ViewModel, vm => vm.StatusFlyout, v => v.StatusFlyout.ViewModel);
```

What am I doing wrong (TM)?

The following works around it:
```
            this.WhenAnyValue(x => x.ViewModel.IsOpen)
                .ObserveOnDispatcher()
                .BindTo(this, x => x.IsOpen);
```

**Comment by paulcbetts** [comment]
If you bind a ViewModel to a View, its threading rules are now the same **as** the View - Bind will not automatically move stuff to the UI thread for you, because of performance

**Comment by sickboy** [comment]
I see, makes sense.
I was expecting it to follow the same principals as the built-in xaml bindings, good to know :)

What's your preference/best practice advice in regards to who will do the marshalling?
The ViewModel who controls the IsOpen property, or the View who binds to the property?

**Comment by paulcbetts** [comment]
@sickboy I would advice only modifying ViewModels on the UI thread, instead of trying to marshal those changes later.

**Comment by sickboy** [comment]
Thanks @paulcbetts
