### ISSUE TITLE
ReactiveUI with Xamarin.Forms

### ISSUE THREAD

**Issue by rajanranjit** [reactiveui/ReactiveUI#924]
I am trying to write some small application with ReactiveUI and Xamarin.Forms. I am getting the following error message when I run 

“You are referencing the Portable version of ReactiveUI in an App. Reference the platform-specific version.”

It compiles fine and only gives this error when starting to load the form.
Does ReactiveUI support Xamarin.Forms.. 
here is the whole stack trace for the error message. Thanks for your help.

System.TypeInitializationException was unhandled by user code
  HResult=-2146233036
  Message=The type initializer for 'ReactiveUI.ReactiveNotifyPropertyChangedMixin' threw an exception.
  Source=ReactiveUI
  TypeName=ReactiveUI.ReactiveNotifyPropertyChangedMixin
  StackTrace:
       at ReactiveUI.ReactiveNotifyPropertyChangedMixin.ObservableForProperty[TSender,TValue](TSender This, Expression`1 property, Boolean beforeChange, Boolean skipInitial)
       at ReactiveUI.WhenAnyMixin.WhenAny[TSender,TRet,T1](TSender This, Expression`1 property1, Func`2 selector)
       at RxUIPoc.ViewModels.MyFirstRxViewModel..ctor()
       at RxUIPoc.Views.MyFirstRxView..ctor()
       at RxUIPoc.App..ctor()
       at RxUIPoc.WinPhone.MainPage..ctor()
  InnerException: 
       HResult=-2146233036
       Message=The type initializer for 'ReactiveUI.RxApp' threw an exception.
       Source=ReactiveUI
       TypeName=ReactiveUI.RxApp
       StackTrace:
            at ReactiveUI.RxApp.EnsureInitialized()
            at ReactiveUI.ReactiveNotifyPropertyChangedMixin..cctor()
       InnerException: 
            HResult=-2146233088
            Message=You are referencing the Portable version of ReactiveUI in an App. Reference the platform-specific version.
            Source=ReactiveUI
            StackTrace:
                 at ReactiveUI.DependencyResolverMixins.InitializeReactiveUI(IMutableDependencyResolver resolver)
                 at ReactiveUI.RxApp.<.cctor>b__0()
                 at Splat.Locator.RegisterResolverCallbackChanged(Action callback)
                 at ReactiveUI.RxApp..cctor()
            InnerException:

**Comment by michaelstonis** [comment]
@rajanranjit you need to add ReactiveUI to all of your projects, including the Xamarin.iOS and Xamarin.Android projects.

**Comment by rajanranjit** [comment]
Thanks.. it works fine now
